### ISSUE TITLE
Any plans to add support for element-wise max?

### ISSUE THREAD

**Issue by mbasmanova** [xtensor-stack/xsimd#1013]
I need to compute an element-wise max and I see that there are Intel intrinsics for that:

```
__m128i _mm_max_epi8 (__m128i a, __m128i b)
__m256i _mm256_max_epi8 (__m256i a, __m256i b)

Compare packed signed 8-bit integers in a and b, and store packed maximum values in dst.
```

and similar.

I wonder if xsimd already has an API for element-wise max / min. I looked in the documentation, but didn't find it. Would it make sense to add?

As a workaround, I'm currently using le + select.

```
auto lt = xsimd::lt(batch, otherBatch);
auto maxBatch = xsimd::select(lt, otherBatch, batch);
```

CC: @kgpai @Yuhta

**Comment by serge-sans-paille** [comment]
yeah, we already have this: 
https://xsimd.readthedocs.io/en/latest/api/math_index.html#_CPPv4I00E3max5batchI1T1AERK5batchI1T1AERK5batchI1T1AE
https://xsimd.readthedocs.io/en/latest/api/math_index.html#_CPPv4I00E3min5batchI1T1AERK5batchI1T1AERK5batchI1T1AE

**Comment by mbasmanova** [comment]
@serge-sans-paille Thank you for the pointer. I missed these somehow. Appreciate a quick response.
