### ISSUE TITLE
Benchmark prints a "neon" result (presumably SSE) on an x86 machine

### ISSUE THREAD

**Issue by HadrienG2** [xtensor-stack/xsimd#102]
~I think the tile says it all :)~

When running "make/ninja xbenchmark" on my Haswell-based machine, a pair of "neon" rows is present in the table of timings, even though this CPU certainly has no neon instructions available.

**Comment by HadrienG2** [comment]
That... was a different bug! :face_with_head_bandage: Will teach me to write descriptions in my tickets...

The bug which I am actually observing is that on my Haswell-based machine, a pair of "neon" rows is present in the table of timings, even though this CPU certainly has no neon instructions available.

**Comment by yunhua-deng** [comment]
I am curious about this issue too, but there is still no answer after 1 year?
Here is `xsimd_benchmark`'s output, which shows neon rows, even though it is on x86 machine.
```
============================
fdim
scalar float   : 0.166787ms
sse float      : 0.006347ms
sse float unr  : 0.005641ms
avx float      : 0.004584ms
avx float unr  : 0.003526ms
neon float     : 0.008462ms
neon float unr : 0.007757ms
scalar double  : 0.171724ms
sse double     : 0.016573ms
sse double unr : 0.020451ms
avx double     : 0.017278ms
avx double unr : 0.015162ms
neon double    : 0.018689ms
neon double unr: 0.014457ms
============================
```

**Comment by SylvainCorlay** [comment]
Yep, this is very strange. This isssue fell between the cracks as it was closed by mistake.

**Comment by serge-sans-paille** [comment]
We no longer have the issue, and I took this issue as an opportunity to cleanup becnhmark display a bit, cf. #876
