### ISSUE TITLE
Doc for Conditional Expression malformed

### ISSUE THREAD

**Issue by themightyoarfish** [xtensor-stack/xsimd#1029]
The doxygen here https://xsimd.readthedocs.io/en/latest/api/batch_manip.html does not seem to render correctly.

**Comment by WarrenWeckesser** [comment]
There is also a problem on the dispatching page: https://xsimd.readthedocs.io/en/latest/api/dispatching.html

**Comment by serge-sans-paille** [comment]
How strange: everything displays correctly when I build the doc locally. It looks like a configuration issue on rtd part, I'll have a look.
