### ISSUE TITLE
Feature request: Reduction sum operator for batch_bool

### ISSUE THREAD

**Issue by degasus** [xtensor-stack/xsimd#1042]
Hi,

in my SIMD loop, I need to query the amount of active lines. I'm currently using a combination of `batch_bool::mask()` and `std::countr_one`, `__builtin_ctz(~batch)` or `_bit_scan_forward(~batch)` depending on compilers.

What is your opinion on having this functionallity within xsimd? Like
```
template<class T, class A> XSIMD_INLINE int sum (batch_bool< T, A > const &x) noexcept
```

Thanks a lot

**Comment by serge-sans-paille** [comment]
I like the idea. Just to be sure of the expected semantic, is this equivalent to `std::popcount(batch_bool::mask())`?

**Comment by serge-sans-paille** [comment]
I'm unsure about the name though, `sum` doesn't seem right.

**Comment by degasus** [comment]
Yes, popcount sounds perfect. Maybe we should just pick the same name `batch_bool::popcnt`?

**Comment by serge-sans-paille** [comment]
I've settled for `count_true` which is as explicit as it can be :-)
