### ISSUE TITLE
scatter and gather instructions

### ISSUE THREAD

**Issue by wolfv** [xtensor-stack/xsimd#106]
It could be interesting to support intels scatter and gather instructions (however, scatter does seem to be available only since AVX512).

**Comment by HadrienG2** [comment]
It's actually even an extension of AVX-512 which was not there on day one :)

But yes, you may want to support it, especially since it has been supported for a long while in the non-Intel world (from the 1st-gen Crays to GPUs).

**Comment by amyspark** [comment]
We have an use case that would benefit of these. Currently we can make do with zip_lo and zip_hi, but I believe it's a bit error-prone.
