### ISSUE TITLE
Velox compile error with xsimd on on RISCV-64

### ISSUE THREAD

**Issue by Ag-Cu** [xtensor-stack/xsimd#1073]
I tried to compile velox with xsimd, but I got the following error, this is a part of the code:

https://godbolt.org/z/s93YKdKez

such code can be compiled successfully on arm64 platform, see :

https://godbolt.org/z/W5seM1f5a

Is there any missing part of current rvv support?

**Comment by wangpc-pp** [comment]
I reported the same issue to velox: https://github.com/facebookincubator/velox/issues/11868

**Comment by serge-sans-paille** [comment]
Why would one use a `reinterpret_cast here`? The right approach is probably to use a `xsimd::bit_cast`, as shown in https://godbolt.org/z/aohazPMM6

**Comment by Ag-Cu** [comment]
Thank you, indeed, perhaps we should change the upstream code.
