### ISSUE TITLE
Implement cumulative sum/prod ... using SIMD

### ISSUE THREAD

**Issue by wolfv** [xtensor-stack/xsimd#108]
We have a prototype for a cumulative sum using xsimd here: https://gist.github.com/jpivarski/b2a04778124e7dc790d87fcdfd399e1e/ 

We should work to integrate it into the library.

**Comment by serge-sans-paille** [comment]
xsimd no longer bundles algorithms, that's something that should go in https://github.com/xtensor-stack/xsimd-algorithm
