### ISSUE TITLE
 Use _mm256_cvttps_epi32 instead of _mm256_cvtps_epi32 everywhere

### ISSUE THREAD

**Issue by wolfv** [xtensor-stack/xsimd#132]
`cvttps` uses truncation and 

`3/5 == 0` becomes true which seems to be the default behavior in C++

**Comment by serge-sans-paille** [comment]
That's what we do now :-) see https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/arch/xsimd_avx.hpp#L537
It's not everywhere though, e.g. we use `_mm256_cvtps_epi32` for the implementation of nearbyint
