### ISSUE TITLE
-m32 support for long int

### ISSUE THREAD

**Issue by serge-sans-paille** [xtensor-stack/xsimd#204]
see https://godbolt.org/z/7j7hVU for a minimal reproducer.

**Comment by wolfv** [comment]
Do you need to use long or would int32_t also work?

Otherwise, I guess we could use `sizeof(long) == 4 && std::is_signed<long>` to map to `int32_t` or `int64_t` depending on the architecture.

**Comment by serge-sans-paille** [comment]
> Do you need to use long or would int32_t also work?

It's not about me, it's about xsimd :-) and my guess is that xsimd should
support long.

> Otherwise, I guess we could use sizeof(long) == 4 && std::is_signed<long> to
> map to int32_t or int64_t depending on the architecture.

Yes!

**Comment by JohanMabille** [comment]
AFAIK, on 64bits architecure, `long == int64`, on 32 bits architecture `sizeof(long) == 32` but `long != int32_t`. Also `long` is always signed.

So the easiest solution (the one I am implementing) is to have `batch<int32_t, N>` as the `batch_type` for `long` and add the `load/store` overloads in every `batch` for 32-bit ABI.

**Comment by wolfv** [comment]
But unsigned long might not be signed?

**Comment by JohanMabille** [comment]
Indeed, `unsigned long` is unsigned, and will be mapped to `uint32_t` on 32-bit systems.

**Comment by diorcety** [comment]
Doesn't seem to resolve all the cases:
https://godbolt.org/z/9q5PnY

**Comment by JohanMabille** [comment]
Let's reopen this.

**Comment by serge-sans-paille** [comment]
The extra example, provided by @diorcety (hi btw o/) now passes once updated to 8.x API: https://godbolt.org/z/GEffvnGch
