### ISSUE TITLE
batch_bool kernel `equal` method

### ISSUE THREAD

**Issue by wolfv** [xtensor-stack/xsimd#235]
We shoudl do two things:

1. rename equal method to `eq` so that it matches the regular kernels
2. change the implementation in batch_bool_float kernel to use ! not_equal which is implemented in terms of xor

**Comment by JohanMabille** [comment]
1. I think the methods name in the regular kernels match the specific part in the name of the intrinsics used for implementation. So if we rename `equal` into `eq` we should also rename all the other methods. I don't really see a benefit in doing this, what is important is that `batch_bool_kernel<T, N>` implementations are consistent together, it does not really matter if they're not consistent with regular kernels. It's even easier for grepping ;)

2. Yep, definitely!

**Comment by wolfv** [comment]
I agree, functionality wise it won't make a difference -- I just thought it was weird that we have `equal` vs `eq` in batch_bool vs batch kernels, and `not_equal` vs `neq`. I still think renaming this function so that it matches would be slightly nicer.

**Comment by JohanMabille** [comment]
Ok, but then let's rename other methods so they also match the intrinsics names!
