### ISSUE TITLE
Neon not detected on armv7hl

### ISSUE THREAD

**Issue by JohanMabille** [xtensor-stack/xsimd#295]
As reported in #289, neon instruction set is not detected when building on armv7hl.
A workaround is  `#define XSIMD_FORCE_ARM_INSTR_SET = 70000000` before including any header of xsimd.

**Comment by serge-sans-paille** [comment]
As long as `-march=armv7-a` is defined, this now works properly, see https://godbolt.org/z/7YYGxKxso
