### ISSUE TITLE
Overload +/+=/-/-= operators with right term batch_bool

### ISSUE THREAD

**Issue by balancap** [xtensor-stack/xsimd#313]
It would be very useful to be able to use directly `batch_bool` mask to increment/decrement integer `batch`, using the integer overfull trick. It allows to update a table of indices in only 2 ops.

**Comment by serge-sans-paille** [comment]
I think we could provide `incr` and `decr` instructions with overload for `batch_bool`. Would that fit your needs?

**Comment by serge-sans-paille** [comment]
@JohanMabille I have a (trivial) impelmentation of incr/decr, now I wonder if the version that accepts a mask should be named `xsimd::incr_if(xsimd::batch_bool)` ?

The default implementation would be based on a select, and when possible we would use the trick mentioned above.

At some point we will have the same discussion on conditional load, so I'd rather settle for a good name pattern now :-)

**Comment by JohanMabille** [comment]
Yes I prefer the pattern `xxx_if(batch_bool)` to `xxx(batch_bool)`
