### ISSUE TITLE
_mm256_blendv_epi16 does not exist

### ISSUE THREAD

**Issue by flori-uni** [xtensor-stack/xsimd#320]
The used methods _mm256_blendv_epi16 in 
https://github.com/xtensor-stack/xsimd/blob/a8d6f7855d33d3263a4d7804e990510093c6b457/include/xsimd/types/xsimd_avx512_int16.hpp#L321-L322

do not exist.

**Comment by flori-uni** [comment]
Any idea how to fix the issue? Would be great if there is a solution ... :grin:

**Comment by martinRenou** [comment]
@JohanMabille @wolfv Do you think splitting another time and using [`_mm256_blendv_epi8`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm256_blendv_epi8&expand=453) would be a good idea?

**Comment by JohanMabille** [comment]
No, I think it's a typo due to name inconsistency in intrinsics. I'm working on a fix.

**Comment by martinRenou** [comment]
Ok :) Thanks

**Comment by JohanMabille** [comment]
The fix is actually broken, reopening this issue.
