### ISSUE TITLE
compile fails on knl (Knights Landing)

### ISSUE THREAD

**Issue by ftegenfe** [xtensor-stack/xsimd#324]
When compiling with xsimd it fails on KNL architecture.
uname -a : Linux x 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

gcc: 8.2.1 20180905 (Red Hat 8.2.1-3)
xsimd git hash: commit af9c6723b7eba63da88e42bf69baf80b601c6007
cpu: Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz

Example code:
`#include <xsimd/xsimd.hpp>`
`int main(int argc, char **argv) {`
`return 0;`
`}`

Compiled with 

g++ std=c++17 -march=knl tst.cpp

yields the compile error in the following log:
[err_knl.txt](https://github.com/xtensor-stack/xsimd/files/3879842/err_knl.txt)

The problem arises in

> kernel::select(cond(), a(), b());

where types are not matching (unsigned vs signed).

**Comment by flori-uni** [comment]
Same problem as #315

**Comment by ftegenfe** [comment]
OK, though I dont see quite the same situation - it's in the same region of the code.
The error I see relates to mismatch in argument types. The code I tested is the latest from github.
> xsimd/types/xsimd_avx512_conversion.hpp:47:5:   required from here
> xsimd/types/../types/xsimd_base.hpp:1625:30: error: no matching function for call to 
> xsimd::detail::batch_kernel<unsigned char, 64>::select(const xsimd::batch_bool<signed char, 64>&, const xsimd::batch<unsigned char, 64>&, const xsimd::batch<unsigned char, 64>&)’
         return kernel::select(cond(), a(), b());
                ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~

**Comment by ftegenfe** [comment]
I made a temp hack that seems to work...
I noticed the error only when expanding XSIMD_DEFINE_BITWISE_CAST_ALL
for the cases with int16_t and int8_t. Commenting out those lines made the compile work.

`#define XSIMD_DEFINE_BITWISE_CAST_ALL(NMIN)                                    \`
`   XSIMD_DEFINE_BITWISE_CAST_FLOAT(double, NMIN)                              \`
`   XSIMD_DEFINE_BITWISE_CAST_FLOAT(float, NMIN * 2)                           \`     
`   XSIMD_DEFINE_BITWISE_CAST(int64_t, NMIN)                                   \`
`    XSIMD_DEFINE_BITWISE_CAST(uint64_t, NMIN)                                  \`
`    XSIMD_DEFINE_BITWISE_CAST(int32_t, NMIN * 2)                               \`
`    XSIMD_DEFINE_BITWISE_CAST(uint32_t, NMIN * 2)                              \`
`    //    XSIMD_DEFINE_BITWISE_CAST(int16_t, NMIN * 4)                  \          `                                                                                                                                                                                                                                                         
`    XSIMD_DEFINE_BITWISE_CAST(uint16_t, NMIN * 4)                              \`
`    //    XSIMD_DEFINE_BITWISE_CAST(int8_t, NMIN * 8)                   \           `                                                                                                                                                                                                                                                        
`    XSIMD_DEFINE_BITWISE_CAST(uint8_t, NMIN * 8)`

Not sure of what other consequences this may cause.

**Comment by JohanMabille** [comment]
@ftegenfe can you confim that #329 fixes your issue?

**Comment by ftegenfe** [comment]
just tried the fix and it works! Thanks for the quick response and an excellent package.

**Comment by JohanMabille** [comment]
Ok no I think this was also the root cause for #315 but let's confirm that later when we set additional configuration for testing other avx512 instruction set.
