### ISSUE TITLE
Use _mm512_scalef_ps for ldexp

### ISSUE THREAD

**Issue by fritterhoff** [xtensor-stack/xsimd#331]
Currently, ldexp gets approximated... AVX512F Provides a new intrinsic for this case: _mm512_scalef_ps

Maybe that could be included? 😉

**Comment by wolfv** [comment]
Would you be interested in providing a PR for this? That would be awesome! 

Btw. thanks for filing all these bugs, it's very helpful!

**Comment by wolfv** [comment]
Would you be interested in providing a PR for this? That would be awesome! 

Btw. thanks for filing all these bugs, it's very helpful!
