### ISSUE TITLE
Use mm_cmpgt_epuXX for unsigned integer comparison on AVX512

### ISSUE THREAD

**Issue by wolfv** [xtensor-stack/xsimd#346]
AVX 512 added some SSE and AVX2 sized instructions for comparing unsigned integers.

The catch is that they return a `__maskX` and not a SIMD register size batch of bool ... so far we don't handle that.

But we could remove the xor flipping code that we currently need in order to use the signed comparisons for unsigned integers.

**Comment by serge-sans-paille** [comment]
We already do that, see https://github.com/xtensor-stack/xsimd/blob/7eb009bca73e5cc51d05dcfcda25dfb74d6e0aaa/include/xsimd/arch/xsimd_avx512bw.hpp#L37
