### ISSUE TITLE
Add a word about alignment requirements of arrays to documentation

### ISSUE THREAD

**Issue by avitase** [xtensor-stack/xsimd#347]
Maybe you could add a word or two to your documentation concerning the alignment requirements of `xsimd::load_aligned` and a best practice for `std::array`, similar to the example for `std::vector`? Could you comment on whether it is ok to use `alignas(XSIMD_DEFAULT_ALIGNMENT) std::array<..., ...>` or not? If not, how could I use `xsimd::load_aligned` for arrays without manually looking up the alignment requirements of a given platform?

**Comment by JohanMabille** [comment]
Good suggestion!

Regarding `std::array` it is definitely ok (actually it is the way to go) to use `alignas(XSIMD_DEFAULT_ALIGNMENT) std::array<..., ...>`.

I will update the documentation as soon as I have the time to do it.
