### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by tort-dla-psa** [xtensor-stack/xsimd#353]
I'm trying to build a C++ project with xsimd, but I get this:
>/usr/local/include/xtensor/xcomplex.hpp:165:41: error: ‘**xsimd**’ does not name a type; did you mean ‘**xt_simd**’?
   ->constexpr X conj_impl(const **xsimd**::simd_complex_batch<X>& z)
/usr/local/include/xtensor/xcomplex.hpp:172:49: error: ‘xsimd’ was not declared in this :  
   ->xtl::negation<std::is_base_of<**xsimd**::simd_complex_batch<T>, T>>
/usr/local/include/xtensor/xcomplex.hpp:172:49: note: suggested alternative: ‘**xt_simd**’

..and so on. All the libraries have recent versions, just updated and installed them.

**Comment by JohanMabille** [comment]
Indeed, that's an issue in xtensor. I'm closing this one and keeping track of it in the xtensor repo.
