### ISSUE TITLE
batch should be trivially default constructible

### ISSUE THREAD

**Issue by zhihaoy** [xtensor-stack/xsimd#364]
```cpp
batch_type x[8] = {};
```
It is surprising that the code above does not initialize x to zeros.
This can be fixed by making `batch() = default;`

**Comment by serge-sans-paille** [comment]
Batch are default constructibles, see https://xsimd.readthedocs.io/en/latest/api/xsimd_batch.html#_CPPv4N5xsimd5batch5batchEv

The default constructor doesn't set any value, if you want something, you specify it :-)
