### ISSUE TITLE
Should I use a reference for xsimd::simd_return_type in a functor

### ISSUE THREAD

**Issue by flipchart** [xtensor-stack/xsimd#371]
Noob question. Still getting the hang of C++ :)

Say I have a functor which performs vector addition:

```cpp
using vector_type = std::vector<uint32_t, XSIMD_DEFAULT_ALLOCATOR(uint32_t)>;

struct add
{
    void operator() (xsimd::simd_return_type<uint32_t, uint32_t> lhs, xsimd::simd_return_type<uint32_t, uint32_t> rhs, uint32_t offset, std::vector<vector_type>& destination)
    {
        (lhs + rhs).store_aligned(&destination[0][offset]);
    }
} add;

// Used like so
auto lhs_vector = xs::load_aligned(...);
auto rhs_vector = xs::load_aligned(...);
std::vector<vector_type> result;

add(lhs_vector, rhs_vector, result);
```

Should the functor arguments `lhs` and `rhs` be (const) references, or is pass by value fine? I know the C++ compiler should inline the code, so perhaps it doesn't matter?

Thanks for the amazing library!

**Comment by JohanMabille** [comment]
It does not really matter in your case. I usually pass everything that is larger than (or as the same size as) a `size_t` (which should be the case of `simd_return_type<X, X>`).
