### ISSUE TITLE
Runtime detection of instruction set

### ISSUE THREAD

**Issue by abique** [xtensor-stack/xsimd#374]
Hi,

I am wondering if it is possible to perform a runtime detection of the instruction set to use?
Basically the approach would be:
```C++
template <typename vector_type>
struct processor
{
  // ...
};

template <typename vector_type>
processor<vector_type> *create_processor()
{
   return new processor<vector_type>();
}

auto *processor = xsimd::native_dispatch<create_processor>();
```

I'm not sure if this is already possible, after reading the examples I've concluded that it isn't.

To be clear, my goal is to produce one executable that will be able to take advantage of the best instruction set available, with the lowest overhead possible.

Many thanks, and I hope that was the right way to ask.

Regards,
Alexandre

**Comment by abique** [comment]
When reading this file: https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/types/xsimd_avx512_float.hpp
it seems that you'd need to move the delcarations inside a `_xsimd::avx512` namespace, that way you could have multiple instructions set support at the same time without have conflicts rights?

And you can do `using xsimd = _xsimd::avx512;` at the very end.
What do you think?

**Comment by JohanMabille** [comment]
I don't think you need to move the declarations of any `batch` class into another namespace. All these classes are different specializations of a template class and can live together (and they actually do on processors that support all of them).

Regarding runtime detection, you can get the supported instructions via `cpuid` and then return a processor that will build / return the appropriate batch type.

**Comment by abique** [comment]
So if we want to have every intel options, we compile with -mavx512 -mtune=generic, and then we could implement the dynamic dispatch.

Do you think that the dynamic dispatch could be part of the library?

**Comment by JohanMabille** [comment]
Yes that would be awesome!

**Comment by abique** [comment]
I close the issue as I might not need it anymore.

**Comment by rgommers** [comment]
Runtime CPU capability detection and dispatch is a fairly essential feature when you're shipping a library to end users via a packaging system. Otherwise all you can do is use the lowest common denominator (probably SSE4 right now, at least for something as widely used as NumPy). Unless this is implemented already, would it make sense to reopen this feature request?

In case it's helpful, here's how NumPy does this currently: https://numpy.org/devdocs/reference/simd/simd-optimizations.html#understanding-cpu-dispatching-how-the-numpy-dispatcher-works.

**Comment by JohanMabille** [comment]
> Unless this is implemented already, would it make sense to reopen this feature request?

We haven't implemented it already, so it definitely make sense to reopen this. However, I wonder if we should implement it in a dedicated package. I could make sense for header-only downstream packages such as xtensor to not depend on binary files.

> In case it's helpful, here's how NumPy does this currently

Thanks for the pointer, that's super helpful!

**Comment by serge-sans-paille** [comment]
Is the use case somehow similar to that: https://godbolt.org/z/Me3xGvW4b ? I'd like to be sure of the intended usage :-)

**Comment by rgommers** [comment]
Pretty much I think. It needs a cache for `getBestInstructionSet` I guess to make it performant, but the principle seems right.

**Comment by drew-parsons** [comment]
xsimd is now packaged for Debian GNU/Linux.  We'd appreciate this kind of functionality, it could greatly improve the value of client libraries such as dolfinx.

**Comment by serge-sans-paille** [comment]
This is now part of 8.0.0, see https://xsimd.readthedocs.io/en/latest/api/dispatching.html

**Comment by drew-parsons** [comment]
Nice!  Thank you.

**Comment by serge-sans-paille** [comment]
In addition to the `xsimd::dispatch` function mentioned above, #906 introduces `xsimd::best_arch` which provides an easy access to the best supported arch for current compilation unit. This PR also improves documentation on xsimd architecture, which should close this issue :-)
