### ISSUE TITLE
feature request: shuffle

### ISSUE THREAD

**Issue by abique** [xtensor-stack/xsimd#375]
Hi,

I've looked through the documentation, but I did not find a way to perform shuffle operations.
Is that missing? If so is it something that could become part of the library?

Many thanks,
Alexandre

**Comment by JohanMabille** [comment]
Hi,

Indeed `xsimd` does not provide any high level API for shuffling yet. That's a feature we would like to have in the library, but we are not sure of how to implement it because of the combinatory issue.

**Comment by abique** [comment]
What do you mean by combinatory issue?

**Comment by serge-sans-paille** [comment]
xsimd now supports `swizzle`, that shuffles a single vector according to a constant mask. See [the doc](https://xsimd.readthedocs.io/en/latest/api/data_transfer.html#_CPPv4I000_Dp2VtE7swizzleNSt9enable_ifINSt13is_arithmeticI1TE5valueE5batchI1T1AEE4typeERK5batchI1T1AE14batch_constantI5batchI2Vt1AEDp6ValuesE)

**Comment by serge-sans-paille** [comment]
@abique I know we're 3 year late on this one, but could you have a look at #925 and check that you were thinking of something along those lines? Thanks!
