### ISSUE TITLE
Fallback is not fully supported (for ARMv7)

### ISSUE THREAD

**Issue by JannisW** [xtensor-stack/xsimd#379]
First of all, thanks for the amazing library! It's been very helpful.

Recently, I encountered an issue with the fallback mode for the old ARMv7 specification when using doubles. 
In this case the macro `XSIMD_ARM_INSTR_SET` is defined, but `XSIMD_BATCH_DOUBLE_SIZE` is not.

This leads to to the default definition of `simd_traits<double>` to be 
```
using type = double;
using bool_type = bool;
static constexpr size_t size = 1;
```

To achieve full fallback behavior, however, they should be defined as:
```
    template <>
    struct simd_traits<double>
    {
        using type = batch<double, 1>;
        using bool_type = batch_bool<double, 1>;
        static constexpr size_t size = 1;
    };
```

Otherwise calls which are not defined for the primitive types will fail to compile. Examples are the subscript operator `[]`, `xsimd::hadd` or `xsimd::simd_type<double>::size`.

So far I'm defining the according simd_traits manually in case XSIMD_BATCH_DOUBLE_SIZE is not defined. 
The better fix would probably to define XSIMD_BATCH_DOUBLE_SIZE as 1 in the appropriate case:
```
#if XSIMD_ARM_INSTR_SET >= XSIMD_ARM7_NEON_VERSION 
#if XSIMD_ARM_INSTR_SET < XSIMD_ARM8_64_NEON_VERSION 
#define XSIMD_BATCH_DOUBLE_SIZE 1
#endif
#endif
```
Please let me know if I'm missing an important point or if you need more information on any of the mentioned details.

**Comment by JohanMabille** [comment]
Sorry for this super late reply, and thanks for this suggestion, it is indeed the best way to fix it. Notice that this requires `XSIMD_ENABLE_FALLBACK` to be defined, otherwise the specialization `batch<double, 1>` is not defined.
