### ISSUE TITLE
Missing fma implementation for xcomplex

### ISSUE THREAD

**Issue by pesterie** [xtensor-stack/xsimd#387]
See [here](https://godbolt.org/z/adf66o)

**Comment by serge-sans-paille** [comment]
@JohanMabille I'll take that one.

**Comment by JohanMabille** [comment]
@serge-sans-paille notice there is already #388 opened.

**Comment by serge-sans-paille** [comment]
ok, it resembles my implementation, with a few quirks. I'll use it as a basis (and also extend it so support fms and friends). @pesterie are you fine with that?

**Comment by pesterie** [comment]
Hi @JohanMabille & @serge-sans-paille !
@serge-sans-paille yes, sure, feel free to iterate from this !
Will have a look when your done !

**Comment by serge-sans-paille** [comment]
@pesterie implementation available in #445

**Comment by pesterie** [comment]
Sweet @serge-sans-paille ! Thx !
