### ISSUE TITLE
Wrong intrinsic in AVX2 int16 xsimd::select

### ISSUE THREAD

**Issue by woffl** [xtensor-stack/xsimd#389]
Hi,

First of all, big thank you for the excellent xsimd library. Most elegant SIMD wrapper I ever used.

Compilation of my code fails in [line 270](https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/types/xsimd_avx_int16.hpp#L270) of xsimd_avx_int16.hpp.

`No matching conversion for C-style cast from 'const xsimd::detail::int16_batch_kernel<short>::batch_bool_type' (aka 'const batch_bool<short, 16>') to 'int'` (clang)

After checking with Intel's Intrinsics Guide, I think it should be `_mm256_blendv_epi8` instead of `_mm256_blend_epi16`, which also would be consistent with the AVX (not AVX2) fallback in lines 275 and 276.

Br,
Wolf

**Comment by JohanMabille** [comment]
Indeed, thanks for catching this!
