### ISSUE TITLE
Can I define `XSIMD_INSTR_SET_NOT_AVAILABLE` to a useful value?

### ISSUE THREAD

**Issue by emmenlau** [xtensor-stack/xsimd#392]
This is really a minor issue. I like to build code with very pedantic build settings. A very helpful flag for gcc and clang is `-Werror=undef` that helps identify cases where a macro is used in a preprocessor condition but the macro is actually undefined (and would evaluate to zero). Such cases can indicate an very tricky error in case the macro is just not in the current include path.

This warning creates a small hickup in xsimd, in the following line:
https://github.com/xtensor-stack/xsimd/blob/8382ff1858704b4e4bcfe943710800c094ad0c02/include/xsimd/memory/xsimd_load_store.hpp#L670

It seems `XSIMD_INSTR_SET_NOT_AVAILABLE` is undefined and not used anywhere else in the whole project. Is that intentional or a bug? If its intentional, can I define `XSIMD_INSTR_SET_NOT_AVAILABLE` to a useful value?

**Comment by JohanMabille** [comment]
I think it is a bug, the correct condition should be

```cpp
#if XSIMD_X86_INSTR_SET > XSIMD_VERSION_NUMBER_NOT_AVAILABLE
```

**Comment by emmenlau** [comment]
Thanks! I can make a PR!
