### ISSUE TITLE
xsimd::transform not working

### ISSUE THREAD

**Issue by hrant-nurijanyan** [xtensor-stack/xsimd#404]
I tried to use xsimd::transform from your doc on GitHub
```
#include <cstddef>
#include <vector>
#include "xsimd/xsimd.hpp"
#include "xsimd/stl/algorithms.hpp"

namespace xs = xsimd;
using vector_type = std::vector<double, xsimd::aligned_allocator<double, XSIMD_DEFAULT_ALIGNMENT>>;

void mean(const vector_type& a, const vector_type& b, vector_type& res) {
    xsimd::transform(a.begin(), a.end(), b.begin(), res.begin(),
                     [](const auto& x, const auto& y) { (x + y) / 2.; });
}
```
But I get error ```error: assigning to 'double' from incompatible type 'void'
            XSIMD_LOOP_MACRO(load_aligned, load_aligned, store_aligned);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/xsimd/stl/algorithms.hpp:110:32: note: expanded from macro 'XSIMD_LOOP_MACRO'
                out_first[i] = f(first_1[i], first_2[i]);                       \
                               ^~~~~~~~~~~~~~~~~~~~~~~~~```

**Comment by SylvainCorlay** [comment]
I think that you are missing a return statement in your lambda.

**Comment by SylvainCorlay** [comment]
@hrant-nurijanyan thanks for opening the ticket!

I will be closing the issue, but feel free to ask should you have more questions.
