### ISSUE TITLE
Advanced SIMD vs NEON?

### ISSUE THREAD

**Issue by dmikushin** [xtensor-stack/xsimd#406]
Dear all, thanks a lot for working on this great project!

I would like to know what is really meant by ARM NEON support. The ARM vector extension has been known as NEON prior to ARMv8-A. Since ARMv8-A onwards vector instruction sets are called "Advanced SIMD", and are not exactly the same as NEON. So, which one is supported by XSIMD, specifically?

**Comment by JohanMabille** [comment]
Hi,

XSIMD supports both ARMv7 and ARMv8 instruction sets.

**Comment by serge-sans-paille** [comment]
More accurately, we have:

Neon support:  https://xsimd.readthedocs.io/en/latest/api/arch.html#_CPPv4N5xsimd4neonE
Neon for aarch64 support: https://xsimd.readthedocs.io/en/latest/api/arch.html#_CPPv4N5xsimd6neon64E
