### ISSUE TITLE
"doxygenfunction: Unable to resolve multiple matches for function" in documetation pages

### ISSUE THREAD

**Issue by mattip** [xtensor-stack/xsimd#407]
I happened to see the error above in pages l[ike this](https://xsimd.readthedocs.io/en/latest/api/basic_functions.html). This was recently fixed [in breathe](https://github.com/michaeljones/breathe/pull/605), you might want to try updating. If it doesn't help, let me know.

**Comment by JohanMabille** [comment]
Thanks for the update! I'm gonna upgrade to last version of breathe.

**Comment by JohanMabille** [comment]
This is actually a problem in our documentation: at some point we refactored xsimd and forgot to update the documentation accordingly. Thanks for catching it!

**Comment by mattip** [comment]
Hmm. [readthedocs build](https://readthedocs.org/projects/xsimd/builds/12685755/) is failing

**Comment by mattip** [comment]
I think you cannot `conda install`, you have to `pip install`

**Comment by mattip** [comment]
weird, the [conda feedstock](https://github.com/conda-forge/breathe-feedstock/pull/43) update for 4.25.1 seems to be merged...

**Comment by mattip** [comment]
OK, it is a problem with the merge build over at conda-forge.

**Comment by JohanMabille** [comment]
Once the package has been uploaded on conda-forge, it will take around 40 minutes to be available on all the mirrors.
