### ISSUE TITLE
Status of C++ level required unclear

### ISSUE THREAD

**Issue by pitrou** [xtensor-stack/xsimd#413]
Currently the README mentions that C++11 is required. However, the docs [landing page](https://xsimd.readthedocs.io/en/latest/) mentions C++14, and the Github project has a `c-plus-plus-14` tag. Which one is it?

**Comment by JohanMabille** [comment]
Almost all the features require C++11 only (this is a requirement from [Pythran](https://github.com/serge-sans-paille/pythran)).

C++14 is required if you want to support vectorization for [xtl::complex](https://github.com/xtensor-stack/xtl/blob/master/include/xtl/xcomplex.hpp#L140).

Thus we need to update the doc to reflect this.
