### ISSUE TITLE
How can I assign zero to a xsimd::batch type varaible?

### ISSUE THREAD

**Issue by zchrissirhcz** [xtensor-stack/xsimd#414]
Let's say I defined this variable:
```c++
constexpr size_t simd_size = xsimd::simd_type<float>::size;
xsimd::batch<float, simd_size> result;
```
I would like to initialize `result` with zeros, in a simple manner, other than:
```
for (size_t i=0; i<simd_size; i++) {
    result[i] = 0;
}
```

I've searched in the documentation page, but didn't found function that I can use. Maybe I just missed some function ? Or, there is no such a function like `xsimd::zero<float, simd_size>` function?

Thanks.

**Comment by JohanMabille** [comment]
You can initialize a batch from a scalar:

```cpp
xsimd::batch<float, simd_size> result(0.f);
```

This will initialize all the values in the batch with `0`. If you need to assign after the variable has been defined, you can use `operator=` with explicit instantiation from the scalar:

```cpp
using batch_type = xsimd::batch<float, simd_size>;
batch_type result;
// ....
// later in the code
result = batch_type(0.f);
```

**Comment by zchrissirhcz** [comment]
Cool! I like this operator style value assigning.
