### ISSUE TITLE
AVX512 not enabled with clang-8.0

### ISSUE THREAD

**Issue by pitrou** [xtensor-stack/xsimd#422]
See https://github.com/pitrou/arrow/runs/1972721611?check_suite_focus=true#step:8:900
```
In file included from /arrow/cpp/src/arrow/util/bpacking_avx512.cc:19:
/arrow/cpp/src/arrow/util/bpacking_simd512_generated.h:47:14: error: implicit instantiation of undefined template 'xsimd::batch<unsigned int, 16>'
  simd_batch masks(mask);
             ^
xsimd_ep/src/xsimd_ep-install/include/xsimd/types/xsimd_base.hpp:35:11: note: template is declared here
    class batch;
          ^
```

Yet the compilation command has the flags `-march=skylake-avx512 -mbmi2 -mavx512f -mavx512cd -mavx512vl -mavx512dq -mavx512bw`. Does xsimd expect more flags when detecting AVX512?

**Comment by pitrou** [comment]
Here is a similar issue on macOS with AppleClang 12.0.0.12000032:
https://github.com/pitrou/arrow/runs/1972721219?check_suite_focus=true#step:5:570

**Comment by pitrou** [comment]
Ok, the explanation is that, while `__AVX512F__`  is defined, `__GNUC__` is also defined by clang to a value smaller than 6.

**Comment by SylvainCorlay** [comment]
@JohanMabille we may want to do the same trick to detect clang version as in xtensor here.

**Comment by pitrou** [comment]
This simple fix seems to compile fine here (I don't have AVX512 on the CPU to check that runtime works):
```c++
// AVX512 instructions are supported starting with gcc 6
// see https://www.gnu.org/software/gcc/gcc-6/changes.html
#if !defined(XSIMD_X86_INSTR_SET) && (defined(__AVX512__) || defined(__KNCNI__) || defined(__AVX512F__)\
    && (defined(__clang__) || !defined(__GNUC__) || __GNUC__ >= 6))
    #define XSIMD_X86_INSTR_SET XSIMD_X86_AVX512_VERSION

```

**Comment by SylvainCorlay** [comment]
> I don't have AVX512 on the CPU to check that runtime works

Yeah, we have an i9 hanging around. We should be able to test what works there.

**Comment by SylvainCorlay** [comment]
@pitrou FYI 7.5.0 was released by @JohanMabille today, which includes all of the recent fixes with respect to AVX512, saturated arithmetics, etc.

**Comment by pitrou** [comment]
Thank for the heads up. We indeed noticed that all of our issues were fixed!
