### ISSUE TITLE
About  std::vector<double, xsimd::aligned_allocator<double, XSIMD_DEFAULT_ALIGNMENT>> related operations

### ISSUE THREAD

**Issue by XMatrixXiang** [xtensor-stack/xsimd#424]
I found that the following code works correctly, but I don't find similar code logic in the documentation or demo (such as push_back, vector[index]), so I want to make sure that the usage is officially supported.

```cpp
namespace xs = xsimd;
using vector_type = std::vector<double, xsimd::aligned_allocator<double, XSIMD_DEFAULT_ALIGNMENT>>;

using cbatch_type = typename xsimd::simd_traits<double>::type;

vector_type simDoubleVector;
for(size_t index = 0; index < 10000; ++index){
	simDoubleVector.push_back(index * 3.14);
}

for(size_t index = 0; index < 10000; ++index){
	std::cout << simDoubleVector[index] << std::endl;
}
```

**Comment by JohanMabille** [comment]
The `aligned_allocator` ensures the memory hold by the vector is properly aligned. This means that each time you need to reallocate the memory (after a `resize`, or a `push_back` for instance), you use this allocator under the hood, and the vector data can be used with the `load_aligned` API.

**Comment by XMatrixXiang** [comment]
@JohanMabille 
Do you mean that the following logic is incorrect 
`
for(size_t index = 0; index < 10000; ++index){
	std::cout << simDoubleVector[index] << std::endl;
}
`
and should be replaced with the following logic?

`
	using b_type = xsimd::simd_type<double>;
    std::size_t inc = b_type::size;
    std::size_t size = simDoubleVector.size();    
    std::size_t vec_size = size - size % inc;
    for(std::size_t i = 0; i < vec_size; i += inc)
    {
        b_type avec = xsimd::load_aligned(&simDoubleVector[i]);        
        std::cout << avec << std::endl;  
    }
    // Remaining part that cannot be vectorize
    for(std::size_t i = vec_size; i < size; ++i)
	{
       std::cout << avec[i] << std::endl;  
    }

`

**Comment by JohanMabille** [comment]
Both are correct, it depends on what you want to do. If you want to access values in your vector, no need to load the data into simd batches. I you want to perform vectorized computations, you should load them into simd batches, and thanks to the `aligned_allocator`, you can use the `load_aligned` API for that (rather than the `laod_unaligned`API, which always works, but might be slower).

**Comment by XMatrixXiang** [comment]
@JohanMabille 
First of all, thank you very much for your reply.

To understand the performance differences, I did a few simple benchmarks:

`
	static std::vector<float> gValues;
	static void GenerateRandomValues(size_t size) {

		std::random_device rd;
		std::mt19937 g(rd());

		gValues.resize(size);
		for (size_t i = 0; i < size; ++i) {
			gValues[i] = (i * 3.1415926f);
		}
		std::shuffle(gValues.begin(), gValues.end(), g);
	}


	static void DoubleMultiplication(benchmark::State& st) {
		if (gValues.size() == 0) {
			GenerateRandomValues(10000);
		}
		std::vector<double> v;
		for (const auto& ref : gValues) {
			v.push_back(ref);
		}
		const size_t vecSize = v.size();
		for (auto _ : st) {
			for (std::size_t i = 0; i < vecSize; ++i) {
				v[i] = v[i] * v[i];
			}
		}
	}
	BENCHMARK(DoubleMultiplication)->Unit(benchmark::kNanosecond);


	static void SIMDDoubleMultiplication1(benchmark::State& st) {
		if (gValues.size() == 0) {
			GenerateRandomValues(10000);
		}
		namespace xs = xsimd;
		using vector_type = std::vector<double, xsimd::aligned_allocator<double, XSIMD_DEFAULT_ALIGNMENT>>;
		vector_type v;
		for (const auto& ref : gValues) {
			v.push_back(ref);
		}
		for (auto _ : st) {
			for (size_t index = 0; index < v.size(); ++index) {
				v[index] = v[index] * v[index];
			}
		}	
	}
	BENCHMARK(SIMDDoubleMultiplication1)->Unit(benchmark::kNanosecond);


	static void SIMDDoubleMultiplication2(benchmark::State& st) {

		if (gValues.size() == 0) {
			GenerateRandomValues(10000);
		}
		namespace xs = xsimd;
		using vector_type = std::vector<double, xsimd::aligned_allocator<double, XSIMD_DEFAULT_ALIGNMENT>>;
		vector_type v;	
		for (const auto& ref : gValues) {
			v.push_back(ref);
		}	
		for (auto _ : st) {
			using b_type = xsimd::simd_type<double>;
			std::size_t inc = b_type::size;
			std::size_t size = v.size();		
			std::size_t vec_size = size - size % inc;
			for (std::size_t i = 0; i < vec_size; i += inc){
				b_type avec = xsimd::load_aligned(&v[i]);	
				avec = avec * avec;
				xsimd::store_unaligned(&v[i], avec);
			}		
			for (std::size_t i = vec_size; i < size; ++i){
				v[i] = v[i] * v[i];
			}
		
		}
	}
	BENCHMARK(SIMDDoubleMultiplication2)->Unit(benchmark::kNanosecond);


	static void SIMDDoubleMultiplication3(benchmark::State& st) {

		if (gValues.size() == 0) {
			GenerateRandomValues(10000);
		}

		namespace xs = xsimd;
		using vector_type = std::vector<double, xsimd::aligned_allocator<double, XSIMD_DEFAULT_ALIGNMENT>>;
		using cbatch_type = typename xsimd::simd_traits<double>::type;
		vector_type v;	
		for (const auto& ref : gValues) {
			v.push_back(ref);
		}
		auto cbegin = xsimd::aligned_iterator<cbatch_type>(&v[0]);
		auto cend = xsimd::aligned_iterator<cbatch_type>(&v[0] + v.size());
		for (auto _ : st) {
			for (; cbegin != cend; ++cbegin) {
				*cbegin = (*cbegin) * (*cbegin);
			}
		}
	}
	BENCHMARK(SIMDDoubleMultiplication3)->Unit(benchmark::kNanosecond);`

This is the result of the benchmark：
![image](https://user-images.githubusercontent.com/13548583/109259769-dc54a000-7837-11eb-89ab-60eeaf0b2def.png)

I don't understand why the benchmark results。

**Comment by JohanMabille** [comment]
It depends on a lot of things: the compilation flags you use, whether the compiler is able to autovectorize the multiplication in the first function, if the compiler optimize away the result, resulting in a noop (probably the case for the last multiplication function), etc ... Google Bnechmark provides a DoNotOptimize function if I remember correctly, to avoid this kind of optimizations.

You need to check the generated assembly code to understand what is happening under the hood.

**Comment by zhujun98** [comment]
I think you can try a more complicated operation like `pow(a, b)` and then you should see the benefit of SIMD.

There is also some relevant discussion here 

https://stackoverflow.com/questions/42964820/why-is-this-simd-multiplication-not-faster-than-non-simd-multiplication

The explanation is that simple operation like multiplication is memory bandwidth bound. Still, some people argues that it is cpu bound.
