### ISSUE TITLE
batch constructor documentation issue

### ISSUE THREAD

**Issue by blackccpie** [xtensor-stack/xsimd#425]
Hello,

seems like there is a little documentation issue here:

https://github.com/xtensor-stack/xsimd/blob/1df22d69932bfd0f31b92a16afcfdb508432c47d/docs/source/api/xsimd_batch.hpp#L91-L100

Aren't these two constructor's documentations inverted? If `unaligned_mode` is used, src doesn't have to be aligned, am I right?

Regards,

Albert

**Comment by JohanMabille** [comment]
Indeed, good catch! Thanks!

**Comment by blackccpie** [comment]
You're welcome!
