### ISSUE TITLE
Implementation of shuffle functions

### ISSUE THREAD

**Issue by JohanMabille** [xtensor-stack/xsimd#433]
This issue tracks the progress on implementing shuffle functions in xsimd. The aproach is to implement different operations in dedicated functions (similar to what is done in [libscimdpp](https://p12tic.github.io/libsimdpp/v2.2-dev/libsimdpp/w/shuffle.html). If you want to contribute, please reply to this issue with the name of the function you're currently working on.

- [x] zip_hi / zip_lo (@guyuqi): SSE and NEON done, missing AVX and AVX512
- [ ] lrot / rrot (@serge-sans-paille)

**Comment by serge-sans-paille** [comment]
Plus we now have generic implementation for swizzle and shuffle with constant mask :-)
