### ISSUE TITLE
Support of non-x86, non-ARM architectures

### ISSUE THREAD

**Issue by lamyj** [xtensor-stack/xsimd#460]
I'm currently working on the packaging of xsimd in Debian (cf. https://lists.debian.org/debian-science/2021/04/msg00000.html and rest of the thread). We were wondering what the status of non-x86, non-ARM architectures (e.g. PowerPC or MIPS) in xsimd: are those supported (even if the support is only through `XSIMD_ENABLE_FALLBACK`) or is xsimd only assumed to work on x86 and ARM?

**Comment by serge-sans-paille** [comment]
A few fixes are needed in the codebase to support fallback mode when no other instruction set is available. I'll propose a patch this week going that direction.

**Comment by serge-sans-paille** [comment]
Once #461 and #462 land, this should be ok.

**Comment by JohanMabille** [comment]
The fixes have been merged. For now, non-x86, non-arm architectures are supported only through `XISMD_ENABLE_FALLBACK`. We will probably add support for PPC in the near future.

**Comment by lamyj** [comment]
Thank you @serge-sans-paille and @JohanMabille!
