### ISSUE TITLE
Memory usage related to XSIMD

### ISSUE THREAD

**Issue by skeletonyk** [xtensor-stack/xsimd#464]
I was trying to use XSIMD for a vector dot, add operation with the following code: 

```
void Convolution::simd_prod_complex_add(
    const complex_vector_t& a, const complex_vector_t& b, complex_vector_t& res)
{   std::size_t           size = a.size();
    constexpr std::size_t simd_size =
        xsimd::simd_type<std::complex<float_type>>::size;
    std::size_t vec_size = size - size % simd_size;

    for (std::size_t i = 0; i < vec_size; i += simd_size)
    {
        b_type ba = xsimd::load_aligned(&a[i]);
        b_type bb = xsimd::load_aligned(&b[i]);
        b_type res_old = xsimd::load_aligned(&res[i]);
        b_type bres1 = ba * bb;
        b_type bres2 = bres1 + res_old;
        b_type bres2.store_aligned(&res[i]);
    }
    for (std::size_t i = vec_size; i < size; ++i) { res[i] += a[i] * b[i]; }
}
```

When profiling the code I found that over 20Gb of temporary memories are allocated and freed.  I am wondering if there is any way I can preallocate and reuse the same memory to improve the performance? 

Thanks!

**Comment by JohanMabille** [comment]
Hi,

`xsimd` does not allocate heap memory, everything is on the stack. The `load_aligned` and `store_aligned` methods transfer data from memory to registers (and vice versa), but no allocation occurs. Closing this issue since it is not related to xsimd.
