### ISSUE TITLE
Floating point truncated to zero warnings

### ISSUE THREAD

**Issue by lhog** [xtensor-stack/xsimd#474]
```
xsimd/math/xsimd_numerical_constant.hpp:94:5: warning: floating constant truncated to zero [-Woverflow]
     XSIMD_DEFINE_CONSTANT(smallestposval, 1.1754944e-38f, 2.225073858507201e-308)
     ^~~~~~~~~~~~~~~~~~~~~
```

```
xsimd/math/xsimd_rem_pio2.hpp:237:17: warning: floating constant truncated to zero [-Woverflow]
                 2.16741683877804819444e-51, /* 0x3569F31D, 0x00000000 */
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

I have these warnings when I compile my code with included xsimd.hpp under Mingw-G++ 8.1.0

**Comment by JohanMabille** [comment]
This warning does not seem legit, `1.1754944e-38f` and `2.225073858507201e-308` are valid `float` and `double` values. Same for  `2.16741683877804819444e-51` which is a valid value for double.

I can replace the values in the smallestposval with `FLT_MIN` and `DBL_MIN` to be sure. Could you run the following and post the result please?

```cpp
#include <cfloat>
#include <iostream>

int main(int argc, char* argv[])
{
    std::cout << FLT_MIN << std::endl;
    std::cout << DBL_MIN << std::endl;
}
```

**Comment by lhog** [comment]
I was surprised myself. When I replaced `1.1754944e-38f` and `2.225073858507201e-308` as a test with `std::numeric_limits<float>::lowest()` and `std::numeric_limits<double>::lowest()` respectively the first warning went away. If this is novel here, I guess I need to look for source of the issue on my side. Will leave it open for now until I reconfirm.

**Comment by lhog** [comment]
I think it could be used no prob.
As for the second case I have no idea what `2.16741683877804819444e-51` is supposed to represent.

**Comment by lhog** [comment]
```
	ss << std::setprecision(12) << FLT_MIN << std::endl;
	ss << std::setprecision(18) << DBL_MIN << std::endl;

	LOG("Precision info: min:\n%s", ss.str().c_str());
```

```
Precision info: min:
1.17549435082e-38
2.22507385850720138e-308
```

**Comment by serge-sans-paille** [comment]
@lhog I cannot reproduce the issue with 2.16741683877804819444e-51 . I've dig a bit and this is a magic value used internally, we don't want to change it (at all). A reproducer on https://godbolt.org/ would certainly help...

**Comment by lhog** [comment]
Yep, very strange thing. I expect it might be some compiler quirk. My project is unfortunately too big to fit into godbolt.

P.S. I ended up replacing constant from the first warning with `FLT_MIN` and `DBL_MIN` and wrapping constants like this `double(2.16741683877804819444e-51L),` in the second case just to mute the annoying warning.

**Comment by JohanMabille** [comment]
@serge-sans-paille I don't remember why we went with these ard-coded constants instead of using `std::numeric_limits`, I agree it would be more elegant to use this latter.
