### ISSUE TITLE
The first example in the doc failed on my Ubuntu, fixed by including cstring

### ISSUE THREAD

**Issue by votientu** [xtensor-stack/xsimd#482]
Hello,

I tried to run the simple example provided in the documentation. I compiled it with g++ 7.5.0 Ubuntu:

$ g++ -march=native -Iinclude hello_xsmid.cpp -o hello_xsmid

```
#include <iostream>
#include "xsimd/xsimd.hpp"

namespace xs = xsimd;

int main(int argc, char* argv[])
{
    xs::batch<double, 4> a(1.5, 2.5, 3.5, 4.5);
    xs::batch<double, 4> b(2.5, 3.5, 4.5, 5.5);
    auto mean = (a + b) / 2;
    std::cout << mean << std::endl;
    return 0;
}
```

Here is the error:

> In constructor ‘xsimd::arch::detail::supported_arch::supported_arch()’:
> include/xsimd/memory/../config/xsimd_arch.hpp:71:20: error: ‘memset’ was not declared in this scope
>                     memset(this, 0, sizeof(supported_arch));
>                     ^~~~~~
> include/xsimd/memory/../config/xsimd_arch.hpp:71:20: note: suggested alternative: ‘wmemset’
>                     memset(this, 0, sizeof(supported_arch));
>                     ^~~~~~
>                     wmemset

I found out that including cstring library in the hello_xsmid solve the problem.

**Comment by serge-sans-paille** [comment]
Fixed by #484
