### ISSUE TITLE
Compilation errors when enabling XTENSOR_USE_XSIMD

### ISSUE THREAD

**Issue by sagyHarpaz** [xtensor-stack/xsimd#498]
Hi.

I have a program that I wrote with xtensor., on microsoft visual studio.
[compilation_log.txt](https://github.com/xtensor-stack/xsimd/files/6730820/compilation_log.txt)

everything work great (but a little bit slow) when XTENSOR_USE_XSIMD is disable, but when I enabling XTENSOR_USE_XSIMD I got hundreds of compilation errors.

Please help.

attached the compilation log.

**Comment by JohanMabille** [comment]
The master branch of xsimd contains breaking changes, please use version 7.5.0 instead.

**Comment by emmenlau** [comment]
@sagyHarpaz Is this issue still relevant?

**Comment by serge-sans-paille** [comment]
No update from OP *and* this is more of an xtensor issue than an xsimd issue, closing.
