### ISSUE TITLE
Compilation error of benchmarks on Apple M1 

### ISSUE THREAD

**Issue by masteranza** [xtensor-stack/xsimd#501]
Here's the problem:
xsimd/memory/../config/xsimd_arch.hpp:22:10: fatal error: sys/auxv.h: No such file or directory

**Comment by serge-sans-paille** [comment]
Can you try to compile the following on Apple M1:

```
#include <xsimd/xsimd.hpp>

#include <iostream>

int main() {
  auto available_archs = xsimd::available_architectures();
  std::cout << "neon: " << available_archs.neon << "\n"
            << "neon64: " << available_archs.neon64 << "\n";
  return 0;
}
```

and report the result? My understanding is that 1. it should compile and 2. it should return 1 for both architectures.

I don't have an Apple M1 to test it, if anyone does, that would do too.

**Comment by serge-sans-paille** [comment]
We now limit usage of `sys/auvx.h` to linux targets (see https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/config/xsimd_cpuid.hpp#L18) which is not the case of the Apple M1, so we should be fine now, closing.
