### ISSUE TITLE
Not found with conan + cmake_paths

### ISSUE THREAD

**Issue by 0Xellos** [xtensor-stack/xsimd#538]
CMake gives the standard "package not found" error
```
  By not providing "Findxsimd.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "xsimd", but
  CMake did not find one.

  Could not find a package configuration file provided by "xsimd" with any of
  the following names:

    xsimdConfig.cmake
    xsimd-config.cmake

  Add the installation prefix of "xsimd" to CMAKE_PREFIX_PATH or set
  "xsimd_DIR" to a directory containing one of the above files.  If "xsimd"
  provides a separate development package or SDK, be sure it has been
  installed.
```

See minimum failing example: [test.zip](https://github.com/xtensor-stack/xsimd/files/7005358/test.zip).

To make it work, we're using the following patches in a custom conan package: [patch.zip](https://github.com/xtensor-stack/xsimd/files/7005357/patch.zip). I'm not sure if that's the "right" way to fix and it's only a sidenote in other work, but if we could use xsimd from conancenter directly that'd be good long-term.

**Comment by SylvainCorlay** [comment]
Which version of xsimd are you using?

**Comment by 0Xellos** [comment]
We're using 7.4.0 in our patched builds, but it isn't in conancenter now so the example has 7.5.0.

**Comment by SylvainCorlay** [comment]
Thanks, I just wanted to make sure that you are not using master.

This is surprising because xsimd does provide a `xsimdConfig.cmake` . However, we (xtensor and xsimd maintainers) don't maintain the conan packages, but only the conda ones, and it is possible that something is wrong with how this has been packaged for conan.

**Comment by 0Xellos** [comment]
Yeah, that should be the case. Perhaps specifically for the cmake_paths generator.

Where's the right place to put the issue then?

**Comment by serge-sans-paille** [comment]
Closed as we know validate cmake integration, so if any issue remain, it's most likely to be on the packager side.
