### ISSUE TITLE
API changes tracking

### ISSUE THREAD

**Issue by DerThorsten** [xtensor-stack/xsimd#544]
this is just to keep track of the api changes I noticed while refactoring xtensor from xsimd7 to xsimd8

there are some trivial changes
```
    xsimd::load_simd    =>     xsimd::load;
    xsimd::store_simd  =>     xsimd::store;
```
And more complicated ones
` xsimd::set_simd` is similiar to the new `xsimd::broadcast` but the new `broadcast` only takes one template argument.

...to be continued...

**Comment by JohanMabille** [comment]
You meant `xsimd::set_simd` is similat to `xsimd::broadcast`, right?

**Comment by serge-sans-paille** [comment]
We now have a https://github.com/xtensor-stack/xsimd/blob/master/Changelog.rst changelog to keep track of changes \o/
