### ISSUE TITLE
[SSE4] extract_pair performance is very bad

### ISSUE THREAD

**Issue by cyb70289** [xtensor-stack/xsimd#557]
When porting my current simd code from intrinsics to xsimd. I see big performance drop from 6.33GB/s to 1.58GB/s. Most drop comes from `extract_pair`. I build with clang-10, -O3, enabled SSE4_2.

Disassembler shows `extract_pair` is using the fallback code [1], not the optimal code based on `_mm_alignr_epi8`[2]. The optimized code is in ssse3, looks it's not inherited by sse4_2 -> sse4_1 -> sse3 -> sse2 -> ....

[1] https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/arch/generic/xsimd_generic_memory.hpp#L14-L35
[2] https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/arch/xsimd_ssse3.hpp#L23-L45

**Comment by cyb70289** [comment]
@JohanMabille

**Comment by serge-sans-paille** [comment]
Thanks for reporting! Can you share a small snippet that reproduces your issue? I'm esp. interested in the bacth type and the value of the scalar argument.

**Comment by serge-sans-paille** [comment]
Actually found the issue, should be fixed by #559
