### ISSUE TITLE
Typo in xsimd/benchmark/CMakeLists.txt ?

### ISSUE THREAD

**Issue by dhk27182** [xtensor-stack/xsimd#579]
Hi,
I think, there maybe a typo in line 17 of xsimd/benchmark/CMakeLists.txt, which currently is:
`set(XSIMD_INCLUDE_DIR ${xsimd_INCLUDE_DIR})`

Isn't it so, that the variable containing the include path, set in line 22 of `xsimdConfig.cmake` is called `xsimd_INCLUDE_DIRS` - with a trailing "S" ?

At least, for me this fix helped to compile the xsimd-benchmark, without it, it did not find the include files.

**Comment by JohanMabille** [comment]
Indeed it's a typo. Would you like to open a PR to fix it?
