### ISSUE TITLE
Batch subscript operators gone for good in v8?

### ISSUE THREAD

**Issue by julian-parker** [xtensor-stack/xsimd#591]
Myself and some colleagues started to look at what is involved in migrating a bunch of our `xsimd` code from v7 to v8, and one major change that came up is the absence of the `[]` operator for batches. Obviously subscripting into SIMD vectors is bad-practice in general due to the performance impact, but we're using it in a few situations due to the lack of shuffle in `xsimd`. Is this feature definitively gone from the API going forward? If so, what is the suggested approach for replacement? Subscipting the `.data` member? Creating new batches from scalars?

**Comment by serge-sans-paille** [comment]
@JohanMabille I'll update the documentation to make that clear.
