### ISSUE TITLE
Huge performance regression for xsimd 8 on Windows 10, SSE4.2 compared to xsimd 7

### ISSUE THREAD

**Issue by boris-kuz** [xtensor-stack/xsimd#617]
Hi!

I noticed a huge performance regression for a couple of functions on Windows 10 with SSE4.2 batches compared to xsimd 7.
I'm using the profiler that comes with Visual Studio 2019, here's the comparison for xsimd 7 and xsimd 8 for the same code:

xsimd 7:
![image](https://user-images.githubusercontent.com/18011434/138889259-78cb5e72-84d4-4f63-bbae-5507b0cc97ec.png)
xsimd 8:
![image](https://user-images.githubusercontent.com/18011434/138889306-0725a419-4dcc-4f35-a6c7-0350ddaa2a35.png)

The integer next to the percentage refers to "CPU Units", which I think are an absolute measure of how many "CPU Units" a function consumes.

As you can see, the performance seems to be strictly worse across the board. The constructor performance got significantly more expensive, so has `xsimd::pow`. 
Here is the code used to run the tests:

https://gist.github.com/boris-kuz/a4e561a79d27722667d065edbcaba22d

(the same test is run twice, once with `xsimd 8.0.3`, once with `xsimd 7.6.0`)

I am building with the "RelWithDebInfo" configuration, `-O2` on x64 and Visual Studio 2019 16.11.5 with `msvc`. My processor is a AMD Ryzen 7 1700.

I hope this is just a mistake on my end, let me know if I can provide you with any additional information.

Thank you!

**Comment by serge-sans-paille** [comment]
@boris-kuz can you confirm #620 fixes your issue with `/Ob1` ?

**Comment by boris-kuz** [comment]
Sorry about the late response, I was busy with other things. The fix descibed in https://github.com/xtensor-stack/xsimd/issues/644 did the trick. Thank you!
