### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by boris-kuz** [xtensor-stack/xsimd#619]
Hey!

I was wondering on what your policy on contributions is? We have internal implementations for a couple functions not found in xsimd (mostly backports from `boost::simd`), but not for every target. Would it still be helpful to you if we submitted what we have as PRs? Or should I get in touch with one of you directly so we can discuss in detail?

Thank you!

**Comment by JohanMabille** [comment]
Hey @boris-kuz,

PRs are definitely welcome, we can provide some guidance to have your functions working on all architectures (or at least have an acceptable fallback ). Do no hesitate to hop on https://gitter.im/QuantStack/Lobby if you have questions that you want to discuss without going through a long Github issue.

**Comment by serge-sans-paille** [comment]
We now have a `CONTRIBUTING.md` file, I'm going to close that issue, and of course accept updates to that file ;-)
