### ISSUE TITLE
Document to_float and to_int and support casts to/from unsigned types

### ISSUE THREAD

**Issue by amyspark** [xtensor-stack/xsimd#622]
Hi!

I came upon this library while researching replacements for Vc. So far it's worked great, minus a few kinks here and there. However, the lack of intrinsics-backed casts produces a ~5x worse compute times on MSVC between Vc and xsimd-based implementations, even while accounting for hidden casts inside Vc. This performance hit can go as far as 100x if `/Ob1` or lower are used.

As an example:

```
template <bool aligned, class U = typename std::conditional<aligned, xsimd::aligned_mode, xsimd::unaligned_mode>::type>
static inline float_v fetch_alpha_32(const void *data)
{
  uint_v data_i =
      uint_v::load(reinterpret_cast<const uint_v::value_type *>(data), U{});
  return xsimd::batch_cast<float>(data_i >> 24); // this conversion goes through batch_cast(with_slow_conversion)
}
```

Instead of doing an aligned store, a compiler-managed copy, and an aligned load, it could be something as simple as `_mm256_cvtepi32_ps(self)`.

**Comment by serge-sans-paille** [comment]
mmmh, actually, `xsimd` can generate call to `_mm256_cvtepi32_ps`, but only when converting *signed* integers to float, and not *unsigned* integers. Which is definitively the semantic of [`_mm256_cvtepi32_ps`](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-intel-advanced-vector-extensions/intrinsics-for-conversion-operations-2/mm256-cvtepi32-ps.html) but we could do better. Let me try to fix that.

Meanwhile, if you can force the cast of `data_i >> 24` to `int_32` is possible.

**Comment by serge-sans-paille** [comment]
(And note that although usage of `/ObN` family option is arguable, #620 fixes interactions of `xsimd` with `/Ob1`)

**Comment by amyspark** [comment]
> mmmh, actually, `xsimd` can generate call to `_mm256_cvtepi32_ps`, but only when converting _signed_ integers to float, and not _unsigned_ integers. Which is definitively the semantic of [`_mm256_cvtepi32_ps`](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-intel-advanced-vector-extensions/intrinsics-for-conversion-operations-2/mm256-cvtepi32-ps.html) but we could do better. Let me try to fix that.

I just found that xsimd *does* have these sort of casts, through `to_int`/`to_float`, but they are undocumented in readthedocs.

> Meanwhile, if you can force the cast of `data_i >> 24` to `int_32` is possible.

We end up doing that anyway, so I've set the correct types from the beginning. Results look much better now, 50% faster on MSVC than our current implementation on AVX, with a slight slowdown on GCC 11.

**Comment by serge-sans-paille** [comment]
I don't like having redundant operations like that. Shouldn't we just remove `to_float` / `to_int` and only keep `batch_cast`? Or the other way around? @JohanMabille any thohgts?

**Comment by amyspark** [comment]
`batch_cast` is OK but it needs to be augmented for all casts supported by intrinsics. Currently it triggers a 200x slowdown in my benchmark because of the memory-backed roundtrip conversion.

**Comment by serge-sans-paille** [comment]
@amyspark can you check #667? `to_int` / `to_float` now fallsback to `batch_cast`, and most if not all [u]int64 <> double and [u]int32 <> float conversion should be handled

**Comment by amyspark** [comment]
@serge-sans-paille looks good to me! I think all that's left now is adding the relevant Arm bits. (Though, from the look of my own patches here, it'll need some `if defined __ARM_ARCH_8A__ || defined __aarch64__`.

**Comment by serge-sans-paille** [comment]
Done & merged :-)
