### ISSUE TITLE
xsimd doesn't detect FMA on MSVC

### ISSUE THREAD

**Issue by amyspark** [xtensor-stack/xsimd#630]
:wave:

I noticed that with MSVC, FMA is never detected because it relies on the `__FMA__` macro, which is GCC and Clang only.

However, from [this StackOverflow question](https://stackoverflow.com/questions/34265982/automatically-generate-fma-instructions-in-msvc) as well as [this MSDN post](blogs.msdn.com/b/vcblog/archive/2014/02/28/avx2-support-in-visual-studio-c-compiler.aspx), MSVC is indeed able to generate FMA instructions with `/arch:AVX2`.

Would it be possible to add support for it, or should it be force enabled from the outside?

(I cannot supply a Godbolt as an example, because it refuses to compile xsimd.)

**Comment by tomjnixon** [comment]
It's in their docs too: https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=msvc-160

IMO it would be good to detect this in xsimd_config.hpp, otherwise it's easy to end up with worse performance on windows.
