### ISSUE TITLE
List of supported architectures is incorrect

### ISSUE THREAD

**Issue by amyspark** [xtensor-stack/xsimd#637]
:wave:

As of 5f6cc9bae1ab62aec7afcf6a5b10d07d728f872f, the readme claims that the following are supported:

Architecture | Instruction set extensions
-- | --
x86 | SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, AVX, FMA3, AVX2
x86 | AVX512 (gcc7 and higher)
x86 AMD | same as above + SSE4A, FMA4, XOP
ARM | ARMv7, ARMv8

however, FMA3, FMA4, XOP (and SSE4a) are all dropped from the architecture lookup:

https://github.com/xtensor-stack/xsimd/blob/f8c1a032673bbae2222d061bcb0e102d1a9ba930/include/xsimd/config/xsimd_arch.hpp#L162

They are also disabled in the cpuid parsing code:

https://github.com/xtensor-stack/xsimd/blob/f8c1a032673bbae2222d061bcb0e102d1a9ba930/include/xsimd/config/xsimd_cpuid.hpp#L116-L117

https://github.com/xtensor-stack/xsimd/blob/f8c1a032673bbae2222d061bcb0e102d1a9ba930/include/xsimd/config/xsimd_cpuid.hpp#L125-L129

https://github.com/xtensor-stack/xsimd/blob/f8c1a032673bbae2222d061bcb0e102d1a9ba930/include/xsimd/config/xsimd_cpuid.hpp#L134-L135

https://github.com/xtensor-stack/xsimd/blob/f8c1a032673bbae2222d061bcb0e102d1a9ba930/include/xsimd/config/xsimd_cpuid.hpp#L147-L149

and, in the case of XOP and FMA4 (as well as SSE4a) have no corresponding ISA register type-

Same for the Arm architecture, what is being looked up is the NEON instruction set, not armv7 or v8a. This prevents runtime dispatching between e.g. v7l and v8a on 32-bit:

https://github.com/xtensor-stack/xsimd/blob/f8c1a032673bbae2222d061bcb0e102d1a9ba930/include/xsimd/config/xsimd_arch.hpp#L163

**Comment by serge-sans-paille** [comment]
Fixed by 2500d4998738aa8ce7a69679c8f6d1aa32a06816

**Comment by amyspark** [comment]
> Same for the Arm architecture, what is being looked up is the NEON instruction set, not armv7 or v8a. This prevents runtime dispatching between e.g. v7l and v8a on 32-bit:
> 
> https://github.com/xtensor-stack/xsimd/blob/f8c1a032673bbae2222d061bcb0e102d1a9ba930/include/xsimd/config/xsimd_arch.hpp#L163

https://github.com/xtensor-stack/xsimd/blob/74959a87c8a95de6f8e636de92c123b2a538809f/README.md#L37

@serge-sans-paille this bit has not been addressed.

**Comment by serge-sans-paille** [comment]
cc @JohanMabille for the arm part. Should we just update the documentation?
