### ISSUE TITLE
Cannot disable FMA5 when /arch:AVX2, possibly leading to performance loss

### ISSUE THREAD

**Issue by amyspark** [xtensor-stack/xsimd#643]
:wave: 

#631 enables using FMA5 when MSVC compiles against AVX2. However, the way it's done at present implies that it's not possible to override it in order to generate just code targeting `xsimd::avx2`. This is not only essential for dynamic dispatch a function without running into SIGILLS, I'm observing as much as 25% performance loss on our benchmark when compiled with `/arch:AVX2`.

I think this bug applies as well to `XSIMD_WITH_SSE4_2`, which is forcibly enabled by default as well.

**Comment by tomjnixon** [comment]
Just checking, did you mean #631? #635 does allow the dispatch to pick fma5, but only if the cpuid bit is detected, which seems reasonable.

The way I've used this is to define a macro from cmake (or wherever) containing the architecture to compile for, and use that in explicit template instantiations -- that way you're not depending on the `default_arch` detection, and you get a more obvious error if something gets screwed up.

In your case where FMA5 is worse than AVX2 (which sounds really suspicious to me), you could just remove it from the list of architectures passed to dispatch.

**Comment by amyspark** [comment]
> Just checking, did you mean #631
Yeah, I just fixed the ref.

> does allow the dispatch to pick fma5, but only if the cpuid bit is detected, which seems reasonable.
I don't use the dispatch functor, we rely on default_arch for individual unit compilation and call architecture-specific versions manually.

> In your case where FMA5 is worse than AVX2 (which sounds really suspicious to me), you could just remove it from the list of architectures passed to dispatch.

Same as above re: dispatcher. I'll share a benchmark later as a demo.

**Comment by serge-sans-paille** [comment]
Can you share a godbolt example? First, disabling fma5 at xsimd level won't prevent the compiler to (eventually) generate such instructions when it thinks it's valuable. Second, I'd like to understand why FMA5 instruction lead to performance penalty. FMA5 "just" introduces fma family instructions, I hardly see how they could not be beneficial...

**Comment by serge-sans-paille** [comment]
@amyspark I recently merged a patch that provides three different variant for FMA architecture: `fma<sse4.2>`, `fma<avx>` and `fma<avx2>`. Can you check this matches your expectations?

**Comment by amyspark** [comment]
@serge-sans-paille I'll check with an updated xsimd and let you know!

**Comment by amyspark** [comment]
Coming back with results @serge-sans-paille.

In GCC and Clang, it works! In MSVC, the configuration header still trumps my command-line `-DXSIMD_WITH_FMA3_<arch>=0`. If each definition had a `!defined XSIMD_WITH_<macro>` check beforehand it would be enough for overriding xsimd.
