### ISSUE TITLE
error_gamma_test/fallback_double.gamma test failing on Intel OSX

### ISSUE THREAD

**Issue by boris-kuz** [xtensor-stack/xsimd#648]
Hey!

I've noticed that the `error_gamma_test/falback_double.gamma` test is failing on the master branch and the release-tags. This is the output I'm getting:
```
Note: Google Test filter = error_gamma_test/fallback_double.gamma
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from error_gamma_test/fallback_double, where TypeParam = xsimd::batch<double, xsimd::fma5>
[ RUN      ] error_gamma_test/fallback_double.gamma
/Users/boris.kuznetsov/dev/xsimd/test/test_error_gamma.cpp:141: Failure
Expected equality of these values:
  diff
    Which is: 7
  0
  while testing lgamma (negative input)
[  FAILED  ] error_gamma_test/fallback_double.gamma, where TypeParam = xsimd::batch<double, xsimd::fma5> (11 ms)
[----------] 1 test from error_gamma_test/fallback_double (11 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (11 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] error_gamma_test/fallback_double.gamma, where TypeParam = xsimd::batch<double, xsimd::fma5>

 1 FAILED TEST
```

I configured the tests with `cmake .. -DDOWNLOAD_GTEST=ON` and build and ran them with the following command `make xtest`. I'm running BigSur, using GNU make 3.81.

The tests build & run fine on x86 Windows and Linux.

**Comment by emmenlau** [comment]
This seems to be not an exact duplicate, but closely related to #456.

**Comment by amyspark** [comment]
I can confirm too on BigSur, though my target arch is `fma3<avx2>`. I see CI doesn't run FMA instructions, perhaps there's an issue there?

**Comment by amyspark** [comment]
UPD: issue is equally reproducible with `CMAKE_CXX_FLAGS="-march=native -mno-fma"` and commenting the avx2 functions out. There seems to be a mistake or a codegen error on AppleClang with AVX instructions when the target architecture includes AVX2.
