### ISSUE TITLE
Indexing and replacing a single batch element in xsimd8.

### ISSUE THREAD

**Issue by franPul** [xtensor-stack/xsimd#658]
Hi all, 
Since version 8, I am missing the handful `operator[]` functionality. In version 7, apart from providing a way of indexing batches, it would also provide a l-value, so you could write something like, 
```
xsimd::batch<int, 4> vInt4{1,2,3,4};
vInt4[0] = 2;
```
I wonder what's the best way to get something similar in version 8. As suggested in the migration guide, one could store the register into an array, modify the array as desired, in this case replacing a single element of the array, and then loading the modified array into the batch again.
That would work, but I am wondering if there is a way to get a `l-value` with `xsimd::batch<T>::get(size_t)`.

Thank you!!

**Comment by serge-sans-paille** [comment]
sse4.1 has this `_mm_insert_ps` intrinsic that could mimic with something like

```
template<typename T, typename A, size_t I>
xsimd::batch<T, A> xsimd::insert(xsimd::batch<T, A> r, T val, index<I> pos);
```

@JohanMabille what do you think?

**Comment by amyspark** [comment]
@serge-sans-paille @JohanMabille this is a (potentially horrible) way of returning a lvalue through a structure enveloping the target batch and the selected index. https://godbolt.org/z/GEe5hKW99

**Comment by serge-sans-paille** [comment]
The resulting code is interesting but probably sub-optimal? Basically a good way to provide the feature would be a `shuffle` with a zeroed buffer followed by an `or`... I'll investigate, thanks @amyspark for suggesting this very templatish solution ;-)

**Comment by amyspark** [comment]
> The resulting code is interesting but probably sub-optimal?

@serge-sans-paille You may find this useful: https://stackoverflow.com/questions/67200087/how-to-set-a-int32-value-at-some-index-within-an-m128i-with-only-sse2/67200171#67200171
