### ISSUE TITLE
Implement gather/scatters

### ISSUE THREAD

**Issue by amyspark** [xtensor-stack/xsimd#662]
:wave:

Vc allows to do masked loads/stores through an [interleaved memory wrapper](https://vcdevel.github.io/Vc-1.4.2/classVc_1_1Common_1_1InterleavedMemoryWrapper.html).

Unfortunately, replicating this access type outside of AVX is completely out of my reach at present, so it would be great to have it on xsimd.

**Comment by tomjnixon** [comment]
Just in case anyone starts working this, I made a start here: https://github.com/xtensor-stack/xsimd/compare/master...tomjnixon:gather

There's some slightly complicated stuff (and unrelated tidying) in there and I'd like to get my story straight before opening a PR, but it does include something like `InterleavedMemoryWrapper`.

`stride_offset` can be used as the index parameter to `gather`, but is defined in a way that makes fallback code generation efficient if you're on an architecture without gather instructions.

This could probably be merged with #106 , anyway.

**Comment by amyspark** [comment]
You're right there, I'll close this one as a dup.

**Comment by amyspark** [comment]
@tomjnixon could I reuse that code? It looks good enough and only lacks the Arm side of things (which would be a nice way to start tinkering with).
