### ISSUE TITLE
pow broken for 0.

### ISSUE THREAD

**Issue by nilsdeppe** [xtensor-stack/xsimd#684]
Hi!

Thanks for the fantastic library! I'm working on getting xsimd integrated into our code to make sure we won't have any bugs. One thing I've come across is that the implementation of `pow` doesn't work for `0.` when floating point exceptions are enabled. Specifically, I'm doing:

```cpp
const xs::batch<double> a{3., 2., 1., 0.};
const xs::batch<double> b{xs::batch<double>::broadcast(2.)};
const xs::batch<double> c = pow(a, b);
```

As far as I can tell this is caused by the use of `log(abs(self))` in https://github.com/xtensor-stack/xsimd/blob/1cc996ef1c2a0b696acb21d65bc9ed67516a4e07/include/xsimd/arch/generic/xsimd_generic_math.hpp#L1899

This specifically triggers `FE_INVALID`. A simple fix seems to be:

```
batch_type z = exp(other * log(abs(self)
                              + std::numeric_limits<T>::min()));
```

This also works if `FE_UNDERFLOW` is enabled. Some specialization for floating point types might be necessary if the same code is used for integer exponentiation. Of course, this assumes `other` is positive. If not, then I think it should report `nan`.

I'll report any more if I find them (and try to at least suggest a solution!).

Thank you so much!

**Comment by serge-sans-paille** [comment]
We're glad you enjoy xsimd! #688 should do the trick, the implementation is slighter slower than yours but probably more accurate, we can discuss it on the related PR :-)

**Comment by nilsdeppe** [comment]
That looks great, I agree that's a safer and more accurate way to handle it :)
