### ISSUE TITLE
signed shift result (0x80000000) sets the sign bit of the shift expression's type ('int') and becomes negative

### ISSUE THREAD

**Issue by Yuhta** [xtensor-stack/xsimd#717]
```
xsimd/include/xsimd/arch/xsimd_sse2.hpp:545:38: error: signed shift result (0x80000000) sets the sign bit of the shift expression's type ('int') and becomes negative [-Werror,-Wshift-sign-overflow]
                    _mm_set1_epi32(1 << 31)));
                                   ~ ^  ~~
```

**Comment by serge-sans-paille** [comment]
This seems to be fixed in `master` branch:
https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/arch/xsimd_sse2.hpp#L545

**Comment by Yuhta** [comment]
> This seems to be fixed in `master` branch: https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/arch/xsimd_sse2.hpp#L545

Still happens on some lines, e.g. https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/arch/xsimd_sse2.hpp#L549
