### ISSUE TITLE
Releasing 8.1.0

### ISSUE THREAD

**Issue by serge-sans-paille** [xtensor-stack/xsimd#721]
Just a meta-bug to track regression / wish list etc before 8.1.0 release

**Comment by serge-sans-paille** [comment]
cc @amyspark @emmenlau and @JohanMabille

**Comment by emmenlau** [comment]
Thumbs up from my side, I (personally) do not have anything urgent in the pipeline. However I see there are a number of open issues regarding arm, Android and/or Apple M1 support. I can think that many of them are related in some form? Is that something that would be easy to address or nothing for the 8.1.0 release?

**Comment by amyspark** [comment]
:+1:  from my side. Awaiting checks from our Mac and Android devs.

**Comment by amyspark** [comment]
Heads up, I've got a report that AppleClang doesn't completely like the Arm optimizations I made in #708 and #710. I'm preparing the MR and the changes to CI to prevent it from happening again.

**Comment by JohanMabille** [comment]
swizzle fixed, I think we can release when the `nearbyint_as_int` is fixed.

**Comment by amyspark** [comment]
@JohanMabille I'm working on permutes/shuffles/interleaves. It'll take a while, so I'll leave it for the next release.

**Comment by JohanMabille** [comment]
ok.

**Comment by emmenlau** [comment]
Thanks a lot guys, @JohanMabille two thumbs up for the release from my side!

**Comment by JohanMabille** [comment]
xsimd 8.1.0 is out!
