### ISSUE TITLE
assert vs. static_assert in initializer list constructor

### ISSUE THREAD

**Issue by jatinchowdhury18** [xtensor-stack/xsimd#722]
I noticed that the initializer list constructor for `xsimd::batch` throws an assertion if the initializer list size does not match the batch size. Since both the batch size and the list size are known at compile-time, would it be possible to make this a `static_assert`? I was recently migrating some code that had been using a different SIMD wrapper, and having the `static_assert` would have helped me to catch some mistakes a bit earlier in the process.

Btw, thanks to everyone who works to make XSIMD awesome! I've been using the library regularly for a few years now, and absolutely love it :).

**Comment by serge-sans-paille** [comment]
xsimd is C++11, and in C++1, `std::initializer_list<T>::size`` is not constexpr, so no ``static_assert`` :-/

see https://en.cppreference.com/w/cpp/utility/initializer_list/size for reference

**Comment by serge-sans-paille** [comment]
That being said, we could check the C++ version and use a ``static_assert`` if legal, I'll do that :-)

**Comment by jatinchowdhury18** [comment]
Ah, that makes sense. For some reason I had it as `constexpr` since C++11 in my head. Having a compile time check when possible would be fantastic! Thanks again :).
