### ISSUE TITLE
Fast conversion between batch_bool and bit mask

### ISSUE THREAD

**Issue by Yuhta** [xtensor-stack/xsimd#753]
We are recently using xsimd to make our [Velox](https://github.com/facebookincubator/velox) query evaluation engine portable.  One of the gap we found is that there is no convenient way to manipulate `batch_bool` efficiently.

What we do in our project is to convert them to bit mask, manipulate the bit mask, then convert it back to SIMD register.  To achieve fast conversion we need to build some global LUT.  You can refer to our implementation here: https://github.com/facebookincubator/velox/blob/main/velox/common/base/SimdUtil.h#L270-L297

If this aligns with your project's philosophy , we can help integrate the implementation into your project.

**Comment by serge-sans-paille** [comment]
We already have the `mask()` method in `batch_bool_constant`. I'm in favor of matching that for `batch_bool`, would you feel ok contributing that one?

**Comment by serge-sans-paille** [comment]
For the record: I've started working on this
