### ISSUE TITLE
Adjust the rsqrt error range to account for AMD hardware

### ISSUE THREAD

**Issue by amyspark** [xtensor-stack/xsimd#757]
@serge-sans-paille @JohanMabille,

I reported a possible miscodegen error in `test_rsqrt` to Microsoft [here](https://developercommunity.visualstudio.com/t/MSVC-2022-returns-imprecise-results-with/10042325). Turns out, AMD has slight precision issues wrt. Intel, so the test will fail with off-by-one errors for certain inputs.

Would it be possible to set an error range like it's done for the gamma function under AppleClang?

**Comment by serge-sans-paille** [comment]
Sure! Would you mind proposing a patch?
