### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by JohanMabille** [xtensor-stack/xsimd#763]
The documentation for arithemtic operators overload is missing. Also, some pages of the API Reference section seems to be merged into a single page while they should not.

**Comment by wermos** [comment]
It looks to me like the functions inside the `batch` class template aren't documented. The class itself also defines the `load` family of functions:
![image](https://user-images.githubusercontent.com/63574588/171828454-37685d05-d85d-4638-acfe-e80700bf2511.png)
but the documentation doesn't mention that anywhere.

These functions have a different signature than the ones which are [already documented](https://xsimd.readthedocs.io/en/latest/api/data_transfer.html).

**Comment by serge-sans-paille** [comment]
> Also, some pages of the API Reference section seems to be merged into a single page while they should not.

Can you elaborate on that point?

**Comment by JohanMabille** [comment]
THe following pages are merged into a single one (meaning you can scroll down across sections while they should be on dedicated pages):
- Arithmetic operators
- Comparison operators
- bitwise operators
- Mathematical functions
- Reducers
- Miscellaneous

**Comment by serge-sans-paille** [comment]
Thanks! #769 is now ready for review, if @JohanMabille and @wermos can have a look?
