### ISSUE TITLE
Offer: GHA based CI builds

### ISSUE THREAD

**Issue by amyspark** [xtensor-stack/xsimd#764]
Hey @serge-sans-paille @JohanMabille,

Our xsimd support is due to be released soon in Krita 5.1. When I was testing Arm things out, I found it very useful to port Arm versions of the Azure jobs to GHA; plus, I added MSYS options to account for our use of LLVM-MinGW in Windows.

These made it possible to check for build errors without having to PR the changes (to access Azure) and wait ages (for Appveyor's single-job builds).

Would you be interested in a PR to upstream these?

**Comment by serge-sans-paille** [comment]
Sure, go ahead! And thanks for being a first-class user of xsimd ;-)
