### ISSUE TITLE
Use of vpadd in hadd function on NEON

### ISSUE THREAD

**Issue by drewcassidy** [xtensor-stack/xsimd#773]
I noticed that the hadd implementation on NEON uses a series of vpadd calls, instead of a single call to vaddv. Is this intentional? I was going to make a PR to improve this but wanted to make sure it wasn't an intentional choice before I began. I noticed this because clang optimizes this down to a vaddv regardless, but gcc does not

**Comment by serge-sans-paille** [comment]
It's a miss on our side. The latest version of gcc also optimises this to an addv (see https://godbolt.org/z/5rTbsGWKj) , we're waiting for your patch!

**Comment by drewcassidy** [comment]
Nevermind, I wasn't looking in Neon64 and those instructions aren't present on 32 bit. Not sure why I saw what I saw in GCC.
