### ISSUE TITLE
Compile-time dispatch instead of switch-case

### ISSUE THREAD

**Issue by wermos** [xtensor-stack/xsimd#779]
As I pointed out in one of my messages in #775, there are many cases like [this](https://github.com/xtensor-stack/xsimd/blob/c2728632bdfecf1dfc004e7ef9ee908003169948/include/xsimd/arch/xsimd_sse2.hpp#L52), where a switch-case is employed to make the decision of which intrinsic to call, even though this decision could be done at compile-time.

As part of our program to improve debug build performance, as @marzer suggested, and for improving performance overall, this should be changed to using some `std::enable_if` type thing.

**Comment by JohanMabille** [comment]
I think we should run benchmarks and see how / whether this hits performancs before complexifying the implementation.

**Comment by serge-sans-paille** [comment]
We already have a similar system for neon intrinsic, and from a maintenance perspective, a single switch is much easier to maintain / read... I'm personally not in favor of trading ease of maintenance with debug build speed.

**Comment by wermos** [comment]
One thing we could do, which I think would be very nice, is use `if constexpr` if the [`__cplusplus`](https://en.cppreference.com/w/cpp/preprocessor/replace) macro's value is greater than `201703L`, and otherwise, stick to the switch-case statement.

[`if constexpr`](https://en.cppreference.com/w/cpp/language/if) would solve this problem at almost zero cost to ease-of-maintenance.

**Comment by serge-sans-paille** [comment]
I don't mind that, provided we can write a nice compat macro that performs either a switch or a cascade of constexpr if.

**Comment by wermos** [comment]
@serge-sans-paille what are your thoughts on replacing the existing switch statements with an if-clause? Granted, the readability of the code will be hurt _a little_, but doing so would make writing a macro for switching between `if` and `if constexpr` very easy.

Moreover, from what I could tell, it doesn't look like there is really a big difference performance-wise between `switch` and a cascade of `if`s for such a small number of cases.

**Comment by marzer** [comment]
> is use if constexpr if [__cplusplus](https://en.cppreference.com/w/cpp/preprocessor/replace) >= 201703L

@wermos Testing the whole C++ version isn't necessary; compilers should define `__cpp_if_constexpr` with a value >= 201606 when `if constexpr` is supported.

**Comment by wermos** [comment]
> is use `if constexpr` if [`__cplusplus`](https://en.cppreference.com/w/cpp/preprocessor/replace) >= 201703L
>
>> @wermos Testing the whole C++ version isn't necessary; compilers should define `__cpp_if_constexpr` with a value `>= 201606` when `if constexpr` is supported.

The problem with these [feature test macros](https://en.cppreference.com/w/cpp/feature_test) is that they were added in C++20, so it is not neccesarily defined if, for example, a compiler is fully C++17 compliant (meaning they have `if constexpr`) but have no C++20 support yet (meaning these feature test macros don't exist).

**Comment by marzer** [comment]
https://godbolt.org/z/Yznoh9nKT

**Comment by marzer** [comment]
> Do you have any links [...]

I don't; that page has always been my go-to. It has been on cppreference since 2015, though, so I suspect the "C++20" but at the top was more that "oh hey these are all actually official now, whereas they've been pseudo-standard up until this point", a bit like how `#pragma once` is 'non-standard' but supported everywhere that matters.

The feature test macros page in 2015: https://en.cppreference.com/mwiki/index.php?title=cpp/feature_test&oldid=77408

**Comment by serge-sans-paille** [comment]
I like the idea of cascading if. Has the test is trivially constant,  compilers should have no difficulties folding it so the runtime cost at `-O2` should be null.
