### ISSUE TITLE
separate scalar mode tests from full vector tests

### ISSUE THREAD

**Issue by drew-parsons** [xtensor-stack/xsimd#784]
As discussed at https://github.com/xtensor-stack/xsimd/issues/756 and at https://github.com/serge-sans-paille/pythran/issues/1999 ,  xsimd is designed to work in scalar mode on all architectures, even those without SIMD vector acceleration. pythran requires xsimd even on "unsupported" arches in order to access scalar mode.

Currently xsimd tests address full functionality and therefore fail on "unsupported" (SIMD-free) architectures.

The tests are defined in XSIMD_TESTS in test/CMakeLists.txt.  It would be useful if that list of tests could be split into scalar-mode and vector-mode tests (e.g. create two lists, XSIMD_SCALAR_TESTS and XSIMD_VECTOR_TESTS), with some kind of new cmake option to switch off XSIMD_VECTOR_TESTS when running on SIMD-free architectures.

**Comment by serge-sans-paille** [comment]
I've run `for i in *.cpp; do grep XSIMD_NO_SUPPORTED_ARCHITECTURE -q $i || echo $i ; done` in test directory and no sensible file appear, which means that we currently disable all (vector) test on unsupported architecture.

I'll add a test that checks that covers all xsimd official functions and mke sure we provide the scalar version.
