### ISSUE TITLE
Aligned Pool Allocator

### ISSUE THREAD

**Issue by ninnghazad** [xtensor-stack/xsimd#79]
An aligned pool allocator that keeps memory around until explicit flush/cleanup would be a nice additional feature.

**Comment by serge-sans-paille** [comment]
I'm not quite sure of what "keeps memory around" means, but we have an [aligned allocator](https://xsimd.readthedocs.io/en/latest/api/aligned_allocator.html#_CPPv4I0_6size_tEN5xsimd17aligned_allocatorE) and you can build your own pool allocator based on it. I don't think it's xsimd task to provide variants of allocator.
