### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by ArborealAudio** [xtensor-stack/xsimd#802]
Since the replacement of xsimd::hadd(), etc., with xsimd::reduce_add(), etc., the current master branch is not backwards-compatible with libraries that depend on any version of xsimd prior to those commits. Bumping up the version number would allow for backwards-compatiblity and present compatibility with the xsimd library.

**Comment by JohanMabille** [comment]
Indeed, usually we bump the version number when we release.
