### ISSUE TITLE
Neq != for floats/doubles doesnt confirm to IEEE 754

### ISSUE THREAD

**Issue by kgpai** [xtensor-stack/xsimd#805]
The following snippet shows that x != Nan returns false , when its supposed to return true (https://en.wikipedia.org/wiki/NaN#Comparison_with_NaN) . 

```
float nan = std::numeric_limits<float>::signaling_NaN();
float num = 1.0f;
auto numX = d_type::broadcast(num);
 auto nanX = d_type::broadcast(nan);

 auto res = numX != nanX;     //Returns all false
 auto reseq = numX == nanX; //Returns all false. 
```

If this is not intentional , I can provide a PR with fix. Let me know . Thanks ! 
This is atleast true for AVX.

**Comment by mbasmanova** [comment]
CC: @serge-sans-paille @JohanMabille @Yuhta

Folks, can you help look into this issue?

**Comment by JohanMabille** [comment]
I think #806 fixes it.

**Comment by mbasmanova** [comment]
Nice. Thank you @JohanMabille for reviewing and merging the fix.
