### ISSUE TITLE
error_gamma_test fails on macOS

### ISSUE THREAD

**Issue by sifmelcara** [xtensor-stack/xsimd#807]
Hello, I'm packaging xsimd 8.1.0 in Nix package manager (https://github.com/NixOS/nixpkgs/pull/187380), and our CI indicate that both M1 and Intel Mac has 1 test case failed (but they failed on different test case)

aarch64: [link to CI log](https://logs.nix.ci/?key=nixos/nixpkgs.187380&attempt_id=6dec8e29-c4bd-4f44-85d9-e4e9a4de9323)

```
[ RUN      ] error_gamma_test/arm_double.gamma
/tmp/nix-build-xsimd-8.1.0.drv-0/source/test/test_error_gamma.cpp:144: Failure
Expected equality of these values:
  diff
    Which is: 5
  0
  while testing lgamma (negative input)
[  FAILED  ] error_gamma_test/arm_double.gamma, where TypeParam = xsimd::batch<double, xsimd::neon64> (3 ms)
```

x86_64: [link to CI log](https://logs.nix.ci/?key=nixos/nixpkgs.187380&attempt_id=d0eeabd5-2022-4af3-ab17-bdcdb660a217)
```
[ RUN      ] error_gamma_test/fallback_double.gamma
/tmp/nix-build-xsimd-8.1.0.drv-0/source/test/test_error_gamma.cpp:144: Failure
Expected equality of these values:
  diff
    Which is: 3
  0
  while testing lgamma (negative input)
[  FAILED  ] error_gamma_test/fallback_double.gamma, where TypeParam = xsimd::batch<double, xsimd::sse4_1> (6 ms)
```

Do you have any idea? Thank you!

**Comment by sifmelcara** [comment]
Oh, I just noticed that previous person who packaged xsimd in our package manager already disabled "error_gamma_test/sse_double.gamma" test and "error_gamma_test/avx_double.gamma" test due to #456

Could this be a similar issue?

**Comment by SomeoneSerge** [comment]
Have there been any updates on this issue in xsimd 10/11?

**Comment by doronbehar** [comment]
Hello Nixers. `xsimd` update to 11.1.0 happens in https://github.com/NixOS/nixpkgs/pull/246200 .

**Comment by serge-sans-paille** [comment]
I believe #1024 finally fixes it.

**Comment by doronbehar** [comment]
I will fetch #1024 into nixpkgs, but I won't wait for CI this time. Thanks @serge-sans-paille for your help and communication.
