### ISSUE TITLE
xsimd CI configuration on Azure may be broken?

### ISSUE THREAD

**Issue by emmenlau** [xtensor-stack/xsimd#815]
I've just checked the xsimd build on MacOS 11 on Azure. There are some errors in the configure step. I think they come from a malformed variable specification in the Azure build scripts. The errors are of the form:
```
/Users/runner/work/_temp/59a7f23f-b868-426d-b990-38813de3d4be.sh: line 4: cross_compile: command not found
/Users/runner/work/_temp/59a7f23f-b868-426d-b990-38813de3d4be.sh: line 13: enable_xtl_complex: command not found
/Users/runner/work/_temp/59a7f23f-b868-426d-b990-38813de3d4be.sh: line 16: avx: command not found
/Users/runner/work/_temp/59a7f23f-b868-426d-b990-38813de3d4be.sh: line 19: avx512: command not found
/Users/runner/work/_temp/59a7f23f-b868-426d-b990-38813de3d4be.sh: line 22: force_no_instr_set: command not found
/Users/runner/work/_temp/59a7f23f-b868-426d-b990-38813de3d4be.sh: line 25: i686: command not found
```
I've seen problems like this in xtensor, xsimd and xtl before, and I think they may indicate a significant problem. Maybe all architectures and projects should be checked...

These errors are taken from https://dev.azure.com/xtensor-stack/xtensor-stack/_build/results?buildId=5161&view=logs&j=9dbd0879-c657-511f-7127-a1c4482cf1d6&t=405c2517-89ee-527d-b5a8-763a430b821a

**Comment by JohanMabille** [comment]
We read these variables in a script common to all builds, while we define these variables for a few configurations only (more precisely, each of this variable is defined for one or two configurations). Therefore, when trying to read the variable when it is not defined, Azure emits these errors. But it does not prevent the build to run correctly, the can be ignored.

**Comment by emmenlau** [comment]
Ok I see, that's good to know! Maybe the variables could have a default though, just to silence the error?

**Comment by JohanMabille** [comment]
If we can define them for all configuration in a single place and then just override the values we need, that would be a nice improvement indeed. Otherwise, we need to repeat the definitions for every config, and it will make the file more cumbersome to read and maintain.

**Comment by emmenlau** [comment]
Yep, sounds like a nice improvement. Should be considered for the other projects (xtensor, xtl) too.

**Comment by JohanMabille** [comment]
Closing this issue as CI has migrated to GHA.
