### ISSUE TITLE
How to reduce build time?

### ISSUE THREAD

**Issue by cyb70289** [xtensor-stack/xsimd#820]
It costs more than 4 minutes to build xsimd test binary (buildtype=release) on a 32 core skylake server with parallel jobs. Looks most of the time is at linking the binary which is a serialized work.
Though debug build is faster, it's still a bit painful for development.
Can we reduce the build time?

Will separated unit tests save build time?
E.g., a `load_store_test` binary includes load/store unit tests only. If we are debugging load/store code, only this specific target needs be built. And multiple tests can be linked in parallel.

**Comment by serge-sans-paille** [comment]
The slowdown comes from the fact that we include repeatedly all xsimd headers for each compilation unit. Interestingly, forcing a concatenation of all tests and then building them yields very fast compilation time (at the expense of slower recompilation). Not sure that's something we want...
