### ISSUE TITLE
Release candidate 10.0.0rc0

### ISSUE THREAD

**Issue by JohanMabille** [xtensor-stack/xsimd#835]
A new release candidate is available. The main breaking change s the removal of the STL subfolder, the algorithms will live in [xsimd-algorithm](https://github.com/xtensor-stack/xsimd-algorithm). We plan to release 10.0 in one week so that clients can test the release.

**Comment by serge-sans-paille** [comment]
Done as of ff7662714a58371fa084936791578396b584e8f0
