### ISSUE TITLE
Silent bug?

### ISSUE THREAD

**Issue by cyb70289** [xtensor-stack/xsimd#850]
Happen to see this. In the code below, looks template parameters `A` and `T` are reversed and SFINAE may silently skip this function and fallback to non-optimized implementation when calling `scatter<A>(...)`.
https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/arch/xsimd_avx512f.hpp#L1376

Is it possible to catch similar issues as compile time?

**Comment by serge-sans-paille** [comment]
I've been thinking of ways to check this, and apart from a clang-tidy specific checker (or a smart enough regex ?),  I couldn't find one.

At some point I would love to have a declarative specification of what xsimd does for each element of the API (specialized or generic implementation, domain range etc) and from this specification generate most of the tests. We're not there yet though.
