### ISSUE TITLE
The xs::load is unavailable.

### ISSUE THREAD

**Issue by linjiahao962889027** [xtensor-stack/xsimd#866]
In the Visual Studio 2022, the xs::load is unavailable.
C++ standard is C++ 20.
xsimd[core]:x86-windows -> 9.0.1
![image](https://user-images.githubusercontent.com/46292984/203678145-ef3d86c4-2cb3-46a6-b5a1-622c9e523dc8.png)
![image](https://user-images.githubusercontent.com/46292984/203678392-03ca4b0f-b994-4e80-858d-7118732d6694.png)
![image](https://user-images.githubusercontent.com/46292984/203678458-7cf3ba7f-64dc-4f45-84ba-7e78701f5ef0.png)

**Comment by serge-sans-paille** [comment]
Thanks for reporting! Can you share the C++ input, so that we can try to reproduce your issue?

**Comment by serge-sans-paille** [comment]
I can reproduce on godbolt.
This problem is solved in current main branch, see https://godbolt.org/z/PMs58ffr4 
I suggest you use the main branch, or (probably) 10.0.0 release instead of 9.0.1.

**Comment by linjiahao962889027** [comment]
> I can reproduce on godbolt. This problem is solved in current main branch, see https://godbolt.org/z/PMs58ffr4 I suggest you use the main branch, or (probably) 10.0.0 release instead of 9.0.1.

OK. Thank you. I use ```xs:: batch<double, xs:: avx512f>:: load_ unaligned``` replaces ```xs:: load<xs:: avx512f, double>```to solve this problem. Vcpkg may need to upgrade its repository. I installed xsimd using vcpkg.
