### ISSUE TITLE
xsimd install with xtensor dependency results in a broken CMake target file

### ISSUE THREAD

**Issue by amyspark** [xtensor-stack/xsimd#869]
👋 

I've just been told at Krita that Debian (and Ubuntu by extension)'s packaging of xsimd does not work to build Krita. I see in the Debian source that they're using `-DENABLE_XTL_COMPLEX=ON` to enable the xtl dependency, but in the xsimd-targets.cmake file, I read

```
add_library(xsimd INTERFACE IMPORTED)

set_target_properties(xsimd PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "xtl"
)
```

with absolutely no reference to xtl-targets.cmake or the relevant `find_package` line.

I'm not sure if this is a xsimd or Debian packaging issue, but reporting it FYI.

**Comment by JohanMabille** [comment]
Thanks for reporting! I think we should add the xtl dependency in the CMakeLists.txt when `-DENABLE_XTL_COMPLEX=ON` rather than in the targets file.

**Comment by amyspark** [comment]
CMake doesn't generate `find_package` lines for dependencies, the project needs to generate its own Config template. I had the notes ready for a potential fix, but I fell sick and lost them...

**Comment by JohanMabille** [comment]
Ah I think I got it, the call to `find_dependency(xtl)` is called only if we build everything together, not when `xtl` and `xsimd` have altready been installed separately.

> I had the notes ready for a potential fix, but I fell sick and lost them

Sorry to read that, I hope you're feeling better!

**Comment by amyspark** [comment]
> Actually the call to `find_dependency(xtl)` is done in the [xsimdConfig.cmake file](https://github.com/xtensor-stack/xsimd/blob/96a24aecd6f76b3f90dd3b8469a68da1f28a27a5/xsimdConfig.cmake.in#L24) so I'm confused why Krita does not build with xsimd. I tried a local build of xtensor with a dependency on xsimd where `ENABLE_XTL_XOMPLEX` was set and had no issue. Do you have the logs of the error?

https://forum.kde.org/viewtopic.php?f=288&t=176722&p=459505#p459505 and compile line looks like https://invent.kde.org/-/snippets/2224. Both point to `xtl` being passed over as-is without the library being resolved to its proper path.
