### ISSUE TITLE
Reduction products

### ISSUE THREAD

**Issue by nilsdeppe** [xtensor-stack/xsimd#873]
Hi folks!

I hope you're doing well!

I'm working on using xsimd as the ARM backend for Blaze (https://bitbucket.org/blaze-lib/blaze/src/master/) and one of the operations Blaze uses is a product reduction (see https://bitbucket.org/blaze-lib/blaze/src/master/blaze/math/simd/Prod.h). I'm not sure if this is implemented in xsimd and I can't find it in the documentation, but in any case this would be nice to have!

Thank you so much!

Best,

Nils

**Comment by serge-sans-paille** [comment]
Hey @nilsdeppe we have a generic reducer as part of the internal API. It makes sense to me to have it exposed, just needs the confirmation from @JohanMabille

**Comment by nilsdeppe** [comment]
🤯 thanks for implementing this so crazy quickly! :D I really appreciate it!
