### ISSUE TITLE
No changelogs

### ISSUE THREAD

**Issue by ni-eddiemond** [xtensor-stack/xsimd#879]
Sorry if this is a stupid question, but what is the best way to tell what the changes are for a new major version? I can't seem to find any kind of changelog or updated documentation. How can I find out what the major changes are between e.g. version 10.0.0 and 9.0.1 apart from reading through all commits?

**Comment by serge-sans-paille** [comment]
Nothing other that the git log yet, but I +1 we should improve the situation for next release. I'll try to provide one backward.

**Comment by ni-eddiemond** [comment]
That would be extremely helpful, thank you!

**Comment by ni-eddiemond** [comment]
Thanks a lot, this really helps!
