### ISSUE TITLE
AVX-512f FMA support?

### ISSUE THREAD

**Issue by nilsdeppe** [xtensor-stack/xsimd#884]
Hi folks!

I've been looking at some AVX-512f code and it seems like in that case the `xsimd_generic_arithmetic.hpp` is used with an `x * y + z` rather than issuing an `__mm512_fmadd_pd` instruction. Presumably same goes for the other fused operations. Would it be possible get support for FMA with AVX-512F added?

Thanks so much in advance!

**Comment by serge-sans-paille** [comment]
Indeed: https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=fmadd_pd&techs=AVX_512&ig_expand=3308

I'll add that, thanks for pointing this out!
