### ISSUE TITLE
Support for scalar bool functions any, all, none?

### ISSUE THREAD

**Issue by nilsdeppe** [xtensor-stack/xsimd#886]
Hi folks!

I'm writing a bunch of generic code that I want to have working on both `double`s and `simd::batch<double, Arch>` and so function signatures look like:
```cpp
template <typename T>
T foo(const T a, const T b) {
  return ...;
}
```
I need masks in a few places and so I'm trying to do:
```cpp
if (const auto mask = a < b; xsimd::any(mask)) {

}
```
Unfortunately, there's no `xsimd::any(bool)` (I also can't find `none`, `all`).

Would it be possible to add these? Thank you so much!

**Comment by serge-sans-paille** [comment]
Makes sense, I'll add that.

**Comment by serge-sans-paille** [comment]
@nilsdeppe can you confirm #904 works as expected? Thanks!

**Comment by nilsdeppe** [comment]
Yes, I'll give it a try this weekend. Sorry, it's been a busier than expected week!
