### ISSUE TITLE
Clang segfaults during build

### ISSUE THREAD

**Issue by audiovention** [xtensor-stack/xsimd#932]
I'm using xsimd together with the xtensor library. My project builds and runs fine with GCC, however with clang I'm getting compiler segfaults.
This is happening both on linux (Ubuntu clang version 15.0.7) and macOS (Apple clang version 14.0.3 (clang-1403.0.22.14.1)).
Interesting enough on macOS I get the segfault only on Apple Silicon, not on an Intel machine, although it was segfaulting on the intel machine with the previous version of XCode. 

For the moment I can provide this part of the log on linux:

`1.	/home/momchil/workspace/audiovention/controlhub/externals/AVxtensor/externals/xsimd/include/xsimd/arch/./xsimd_sse2.hpp:672:77: current parser token ')'
2.	/home/momchil/workspace/audiovention/controlhub/externals/AVxtensor/externals/xsimd/include/xsimd/arch/./xsimd_sse2.hpp:21:1: parsing namespace 'xsimd'
3.	/home/momchil/workspace/audiovention/controlhub/externals/AVxtensor/externals/xsimd/include/xsimd/arch/./xsimd_sse2.hpp:32:5: parsing namespace 'xsimd::kernel'
4.	/home/momchil/workspace/audiovention/controlhub/externals/AVxtensor/externals/xsimd/include/xsimd/arch/./xsimd_sse2.hpp:652:9: parsing function body 'xsimd::kernel::from_mask'
5.	/home/momchil/workspace/audiovention/controlhub/externals/AVxtensor/externals/xsimd/include/xsimd/arch/./xsimd_sse2.hpp:652:9: in compound statement ('{}')
`

I will try to create a minimum reproducible example. I know this is more of a clang issue than xsimd, but I'd appreciate any possible workaround. 

I'm on tag 11.0.0

**Comment by audiovention** [comment]
Hi again, I have a very good update, I've narrowed it down completely - adding the "-Wcast-align" warning causes the segfaults in clang. If anyone arrives here, just disable this warning for a workaround. 

You can reproduce the issue by adding
`target_compile_options(mandelbrot PUBLIC -Wcast-align)
`
to the examples CMakeLists and compile the examples.
I will create an issue with clang as well.

**Comment by serge-sans-paille** [comment]
I submited a fix upstream :-) https://reviews.llvm.org/D151753
