### ISSUE TITLE
batch(batch_bool) docs don't match implementation

### ISSUE THREAD

**Issue by tomjnixon** [xtensor-stack/xsimd#939]
This test shows that when constructing a `batch` from a `batch_bool`, `true` is mapped to `1`:

https://github.com/xtensor-stack/xsimd/blob/e6fa5aca6320d6ccaf24c123ab2af9b0f2f09cc1/test/test_batch.cpp#L782-L786

However, the say that true is mapped to `0xff`:

https://github.com/xtensor-stack/xsimd/blob/e6fa5aca6320d6ccaf24c123ab2af9b0f2f09cc1/include/xsimd/types/xsimd_batch.hpp#L521-L527

**Comment by serge-sans-paille** [comment]
Thanks for reporting this. The comment is incorrect and the implementation is correct, which only makes sense wrt. scalar behavior.

**Comment by serge-sans-paille** [comment]
Got fixed by 6363da90e2d1ff712e3fc728936e3ca5d409b2e4
