### ISSUE TITLE
CHECK_EQ( extract(xsimd::polar(T(val0), T(val1))), std::polar(val0, val1) ) is NOT correct!

### ISSUE THREAD

**Issue by jcurtis-cc** [xtensor-stack/xsimd#956]
Apple Silicon M1

> [doctest] doctest version is "2.4.9"
[doctest] run with "--help" for options
===============================================================================
xsimd/test/test_xsimd_api.cpp:747:
TEST CASE:  [xsimd api | float types functions]<xsimd::batch<double>>
  polar
>
> xsimd/test/test_xsimd_api.cpp:669: ERROR: CHECK_EQ( extract(xsimd::polar(T(val0), T(val1))), std::polar(val0, val1) ) is NOT correct!
  values: CHECK_EQ( (-1.96093,-2.27041), (-1.96093,-2.27041) )
>
>===============================================================================
[doctest] test cases:  308 |  307 passed | 1 failed | 0 skipped
[doctest] assertions: 8191 | 8190 passed | 1 failed |
[doctest] Status: FAILURE

**Comment by serge-sans-paille** [comment]
How strange... The `polar` function is generic and relies on `sincos`, which itself is generic and tested on all other architectures :-/
I don't have an hint there, we could relax the check?

**Comment by JohanMabille** [comment]
We had the same issue with emscripten, using an [alternative implementation](https://github.com/xtensor-stack/xsimd/blob/master/include/xsimd/arch/generic/xsimd_generic_math.hpp#L981) fixed the issue.

It is less efficient, but more accurate (although I'm not sure to get it, `sincos(a)` should give the same results as `(sin(a), cos(a))`.

**Comment by serge-sans-paille** [comment]
Fixed by #970
