### ISSUE TITLE
Doc search doesn't work

### ISSUE THREAD

**Issue by pitrou** [xtensor-stack/xsimd#965]
The doc search never seems to find results, for example:
https://xsimd.readthedocs.io/en/latest/search.html?q=swizzle&check_keywords=yes&area=default#

Similarly, the version switcher at the bottom left doesn't seem to work here.

**Comment by JohanMabille** [comment]
I've "fixed" the documentation build last week (this was stucked on old version of RTD and old packages), it looks like sphinx_rtd_theme is the culprit.

**Comment by JohanMabille** [comment]
[fc6c3](https://github.com/xtensor-stack/xsimd/commit/fc6c3fbd83831c6575c85208c875f1b24574cbfd) fixed it.
