### ISSUE TITLE
Over branching creation due to specialisation choices

### ISSUE THREAD

**Issue by devnull31** [xtensor-stack/xsimd#968]
Hello there, I am new to xsimd, so sorry if already answered.
In the implementation I understand that XSIMD_IF_CONSTEXPR macro will allow the compiler to choose for a branching when using suitable compiler.
But often this macro is not used for type sign checking like (in xsimd_sse2.hpp) 

`'        // ssub

        template <class A, class T, class = typename std::enable_if<std::is_integral<T>::value, void>::type>
        inline batch<T, A> ssub(batch<T, A> const& self, batch<T, A> const& other, requires_arch<sse2>) noexcept
        {
            if (std::is_signed<T>::value)
            {
                XSIMD_IF_CONSTEXPR(sizeof(T) == 1)
                {
                    return _mm_subs_epi8(self, other);
                }
                else XSIMD_IF_CONSTEXPR(sizeof(T) == 2)
                {
                    return _mm_subs_epi16(self, other);
                }
                else
                {
                    return ssub(self, other, generic {});
                }
            }
            else
            {
                XSIMD_IF_CONSTEXPR(sizeof(T) == 1)
                {
                    return _mm_subs_epu8(self, other);
                }
                else XSIMD_IF_CONSTEXPR(sizeof(T) == 2)
                {
                    return _mm_subs_epu16(self, other);
                }
                else
                {
                    return ssub(self, other, generic {});
                }
            }
        }
``

Here the `if (std::is_signed<T>::value)` won't use `if` `constrexpr` statement, does it mean that a branching will be created and evaluated each time we use `ssub`

**Comment by serge-sans-paille** [comment]
> Here the if (std::is_signed::value)`` won't use if constrexpr statement, does
> it mean that a branching will be created and evaluated each time we use ssub

Generally not, because constant folding is a basic compiler optimization. We
could still enforce this with the macro you mention... Do you feel like
submitting a patch?

**Comment by devnull31** [comment]
Ok thanks, no development planed on my side.
