### ISSUE TITLE
scalar implementation without code duplication

### ISSUE THREAD

**Issue by actual-daniel** [xtensor-stack/xsimd#998]
I'm currently a bit confused about the purpose of `xsimd::generic`. My expectation was that its possible to use this architecture as a fallback or for development purposes.  For this I would assume that `xsimd::batch<T, xsimd::generic>` just contains a single scalar value. But this is not the case - Instead the build fails because `xsimd::has_simd_register` is `false`. 

I could specialize `load_*` and `broadcast` calls and try to separate it from the rest of the implementation which then hopefully works with scalar and simd types. But it feels like this could be abstracted through implementation of the generic architecture. 

Is there a reason why this is not done? Are there examples how to write simd and scalar implementations without duplicating code?

**Comment by serge-sans-paille** [comment]
yeah, generic means "generic vector architecture". It would work with an hypothetical vector of one register, but that architecture fallback doesn't exist.

We do provide overloads for scalar values though, i.e. `xsimd::cos` fallsback to `std::cos` where it makes sense.

**Comment by serge-sans-paille** [comment]
Instead of the "scalar" backend, which would conflict in essence with the scalar overload we provide for every operation, we could have an `emulated<n>` backed that would emulate a batch of `n` elements using scalar operations, relying on the generic implementation etc.

Is that what you have in mind? I'd happily implement that.

**Comment by actual-daniel** [comment]
@serge-sans-paille Yes this is exactly what I was looking for! Using a generic `n` as you suggested would actually be even better than what my initial request was.
